### ISSUE TITLE
export default ArrowArg => {}; Causes highlighting issues

### ISSUE THREAD

**Issue by FuzzOli87** [othree/yajs.vim#100]
![image](https://cloud.githubusercontent.com/assets/12246915/12059089/003beb32-af1a-11e5-8815-7c56234da6b9.png)

As you can see on the left split, the arrow function after React is treated as a regular javascriptOp. I spent sometime playing with the syntax but I couldn't figure out how to add something to deal with this. I have little experience but I was bored. 

It treats React as an identifier instead of a arrow func argument. I believe this is because of how the 'default' keyword only deals with javascriptBlock in the syntax in the 'nextGroup'. I apologize for the bad screenshot, I didn't have a tool installed in my OS and I didn't want to think too hard.

**Comment by othree** [comment]
I also update https://github.com/othree/es.next.syntax.vim for this issue

**Comment by FuzzOli87** [comment]
Awesome. Thanks for the quick fix!
