### ISSUE TITLE
Switch Statement + case + Expression + Block syntax = Bad Highlight

### ISSUE THREAD

**Issue by timoxley** [othree/yajs.vim#104]
Syntax highlight is broken if anything other than a variable is used in a case statement:

![image](https://cloud.githubusercontent.com/assets/43438/12163295/5e5bf90e-b547-11e5-9867-c014fe91da27.png)

It appears that the RHS of a `case` can be any JS expression:

[![image](https://cloud.githubusercontent.com/assets/43438/12163326/a56b6cbc-b547-11e5-837f-6fae1f9a7818.png)](http://www.ecma-international.org/ecma-262/6.0/#sec-switch-statement)

For now, if yajs only supported the first case in the example I think you'd be covering most of your bases… it's the only other case pattern I have in my codebase and IMO the other forms are likely to be much rarer.

```js
switch (Animal) {
  case Ani.mal: {
    const thing = 'what'
    break
  }
}

switch (Animal) {
  case Animal(): {
    const thing = 'what'
    break
  }
}

switch (Animal) {
  case (Animal): {
    const thing = 'what'
    break
  }
}
```

Related to #103

**Comment by othree** [comment]
Of course it should accept all RHS expression.
The problem is I can't make the following `:` be recognized if I just allow all RHS expression(or I will produced lots of duplicated code).
Vim syntax system can't look forward~

**Comment by othree** [comment]
Finally figure out `:` is not an operator.
So much easy to use region for this case.

**Comment by timoxley** [comment]
:dancer: Great stuff, works perfectly.
