### ISSUE TITLE
Try/catch syntax highlighting

### ISSUE THREAD

**Issue by danihodovic** [othree/yajs.vim#106]
Why is there no special syntax highlighting for try/catch? Are there any plans of implementing this?

**Comment by othree** [comment]
There are syntax for try/catch.
But I use wrong group for them[1][].
You could try again.

[1]:https://github.com/othree/yajs.vim/commit/9965b2c946dd6ed774fb7d28f93c91264bfebc1a

**Comment by danihodovic** [comment]
Thanks (y)
