### ISSUE TITLE
identifiers before arrow function in Set constructor are not highlighted correctly

### ISSUE THREAD

**Issue by leomao** [othree/yajs.vim#108]
codes like following are not highlighted correctly.

```js
let s = new Set(arr.filter((x) => { return x.p == 1; }));
//                 ^^^^^^^^^
```

I found that adding `@javascriptExpression` in the `contains` of `javascriptFuncArg` will solve this issue.
But I am not sure if this is the right way to solve this problem.

**Comment by othree** [comment]
It works ok on webidl branch.
I am working on ti now.

**Comment by othree** [comment]
This should be fixed. Please verify again. Thank you.

**Comment by Jerskouille** [comment]
I downloaded the plugin yesterday and it fails on a simple

```js
(() => false)
 ^
```
