### ISSUE TITLE
Highlight group on function args destructuring 

### ISSUE THREAD

**Issue by mikekreeki** [othree/yajs.vim#109]
Both parens (`{}`) and variable name share the same hightlight group (`javascriptFuncArg`), therefore it's not possible to highlight them separately (like on the second line of the example). 

When `hi link javascriptFuncArg Normal`:

![screenshot 2016-01-18 21 24 21](https://cloud.githubusercontent.com/assets/819445/12413790/9cd2b22e-be91-11e5-9078-f32f8834888b.png)

When `hi link javascriptFuncArg javascriptBraces` (in my case):

![screenshot 2016-01-18 21 25 02](https://cloud.githubusercontent.com/assets/819445/12413787/9aa339a6-be91-11e5-9405-a2afee469aef.png)

Same goes in this example:

![screenshot 2016-01-18 22 40 28](https://cloud.githubusercontent.com/assets/819445/12413896/56b07bf4-be92-11e5-9bcc-c391490cf5bf.png)

My goal was to make all variable names white and all parens and braces orange.

What is your opinion on this? Could it be improved?

**Comment by othree** [comment]
Still not support destructing arguments ~

**Comment by mikekreeki** [comment]
Okay, cool. Thanks for info.

**Comment by othree** [comment]
Actually I still don't have good on how to highlight destructing arguments.
Any suggestion?

**Comment by othree** [comment]
I think current support is enough, you can take a try on latest reversion. Thank you
