### ISSUE TITLE
Comments are unhighlighted when semicolon is ommitted

### ISSUE THREAD

**Issue by mcchrish** [othree/yajs.vim#112]
<img width="244" alt="screen shot 2016-01-26 at 4 38 30 pm" src="https://cloud.githubusercontent.com/assets/7200153/12575921/47d51bd0-c44b-11e5-8b0c-e664a6a29484.png">

**Comment by bwot** [comment]
:+1: 
Yeah, I also get this in 2.0. Was about to start an issue about this when I had time. I mentioned it over in #111
