### ISSUE TITLE
comment at the end of the line does not highlight

### ISSUE THREAD

**Issue by leohahn** [othree/yajs.vim#113]
Whenever I try to comment a line

function() {]  // my comment

It does not work. The same problem happens with block comments.

**Comment by othree** [comment]
function() {] // my comment

Is not correct code.
And I cant reproduce this.
Maybe you need provide more lines of code.

**Comment by leohahn** [comment]
Sorry, here is an example that works for me on a new file:

    // Here it works
    import Lib from 'lib'; // Here it does not
