### ISSUE TITLE
Incorrect keyword highlight in nested functions

### ISSUE THREAD

**Issue by snahor** [othree/yajs.vim#114]
![screenshot from 2016-01-29 19 16 05](https://cloud.githubusercontent.com/assets/96594/12691735/e5f7623c-c6bc-11e5-8258-f3cf28287487.png)

This also happens with `let` and `var`.

Ubuntu + vim/neovim

**Comment by othree** [comment]
You need [es.next.syntax.vim](https://github.com/othree/es.next.syntax.vim).
async is not part of ES6, so not in yajs now.

**Comment by mnylen** [comment]
This happens with regular ES6 too.

<img width="473" alt="screen shot 2016-02-02 at 08 14 01" src="https://cloud.githubusercontent.com/assets/49331/12741440/01811de8-c985-11e5-90e7-b7b1ae6a5e54.png">

**Comment by othree** [comment]
@mnylen Please provide code snippets for reproduce the issue.
And I think you can open a new one :)

Thanks~
