### ISSUE TITLE
The parens of arrow functions should be highlighted as javascriptParens

### ISSUE THREAD

**Issue by leomao** [othree/yajs.vim#115]
I found that the parentheses of arrow functions are highlighted as `javascriptArrowFuncDef` in the current master branch.

Shouldn't they be highlighted as `javascriptParens` instead?

**Comment by othree** [comment]
Yes, but current `javascriptParens` is normal group (no special color).

I will fix this issue when supporting destructing parameter

**Comment by leomao** [comment]
Thanks for reply.
Because I use `after/syntax/javascript.vim` to change the colors of some groups, it is a bit strange to highlight `javascriptArrowFuncDef` and `javascriptParens` with the same color. (Although only the parentheses of arrow functions will be highlighted as `javascriptArrowFuncDef`.)

**Comment by othree** [comment]
A good timing for ask for your opinion on parens.
I am trying to support destructing argument #109 
The code will be something like:

    function ({a, b}) {}
    ({a,b}) => {}
    ([a,b,c,d]) => {}

Do you have any idea on how to highlight the `()`, `[]`, `{}` in this code snippets ?

**Comment by leomao** [comment]
I will highlight them as usual (`javascriptParen`, `javascriptBrackets`, `javscriptBraces`) personally.

IMO, I think we can give them special groups so that users can change the color by themselves via `after/syntax/javascript.vim`.
But I'm not sure what the default highlight colors for these groups should be.

**Comment by othree** [comment]
Thank you, now they are normal `javascriptParen`, `javascriptBrackets`, `javscriptBraces`.
No special highlight now.

**Comment by leomao** [comment]
Great! Thanks :smile:

**Comment by leomao** [comment]
Oh, I found that the original problem still exists.
Will this be fixed?

**Comment by othree** [comment]
Yes, fixing
