### ISSUE TITLE
Support ES Class Fields & Static Properties

### ISSUE THREAD

**Issue by emorikawa** [othree/yajs.vim#116]
https://github.com/jeffmo/es-class-fields-and-static-properties

When you create a bound instance method, it breaks the context for all following functions:
![image](https://cloud.githubusercontent.com/assets/489001/12753266/5146ef88-c994-11e5-9599-222fd96e3224.png)

[Babel example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20PostInfo%20extends%20React.Component%20%7B%0A%09handleOptionsButtonClick%20%3D%20(e)%20%3D%3E%20%7B%0A%20%20%20%20this.setState(%7BshowOptionsModal%3A%20true%7D)%3B%0A%20%20%7D%0A%7D)

**Comment by othree** [comment]
Try use yajs and [es.next.syntax](https://github.com/othree/es.next.syntax.vim) together

**Comment by emorikawa** [comment]
Beautiful! Thank you

**Comment by emorikawa** [comment]
I'd put a note about that in the Readme
