### ISSUE TITLE
highlighting breaks on Promise

### ISSUE THREAD

**Issue by strathausen** [othree/yajs.vim#118]
Something strange going on with the highlighting of this code:

```
return {
  x: Promise.x(() => {
    return new Class({})
      .fetch({foo: bar})
      .then(res => {
        let x
      })
      .then((res) => {
        let x
      })
  }
}
```

Looks like
<img width="202" alt="screen shot 2016-02-12 at 23 07 50" src="https://cloud.githubusercontent.com/assets/131341/13075785/1afa5eea-d4ae-11e5-9bfc-4dd8da63a81d.png">

However, when I change `Promise` to something else, e.g. `Pomise`, it renders correctly:

<img width="193" alt="screen shot 2016-02-12 at 23 08 01" src="https://cloud.githubusercontent.com/assets/131341/13075786/1afc14e2-d4ae-11e5-8918-eab61b2ebddc.png">

Thanks for the great work!

**Comment by othree** [comment]
Thank you for report.
Caused by I have a special set for Promise's static method.
And I ignore other custom method/props.

**Comment by strathausen** [comment]
Thank you for fixing this! I've pulled the changes, but I do not yet see them in vim. Do I have to compile something? `make` failed for me (bash syntax error)
