### ISSUE TITLE
!= and !== being marked as invalid syntax

### ISSUE THREAD

**Issue by IN3D** [othree/yajs.vim#119]
I noticed a recent update to my plugins made ```!=``` and ```!==``` operators highlight as as invalid. I believe that this was due to a change in this plugin.

[This line](https://github.com/othree/yajs.vim/blob/master/syntax/javascript.vim#L71) seems to have been the most recent relevant change, and I think it's what has caused this.

I've found two ways to fix this. One involves removing ```javascriptInvalidOp``` as one of the next groups on line 71. The other way, is removing the equal sign from ```javascriptInvalidOp```'s regex expression.

I'd be happy to make a pull request, but I wasn't sure which way would be the best approach for the project.

Here's a screen shot of what I'm experiencing
![screenshot_2016-02-25_17-03-08](https://cloud.githubusercontent.com/assets/5441516/13336789/f8138b60-dbe5-11e5-9fa9-0e90ded51557.png)

**Comment by othree** [comment]
Thank you :)

**Comment by IN3D** [comment]
Awesome, thanks for the quick fix!
