### ISSUE TITLE
Reserved word are red in functions with computed properties

### ISSUE THREAD

**Issue by dak0rn** [othree/yajs.vim#120]
I noticed that reserved words such as `const` or `return` are marked red in functions with a computed property name.

![red-name](https://cloud.githubusercontent.com/assets/3854533/13381566/85470cb6-de5f-11e5-8cb5-dce99afe9f92.png)

I think this could be related to #89.

Disabled all installed plugins but the problem persists.

`:HLT!` output:
```
SynStack:
javascriptObjectLiteral
  ->javascriptObjectLiteral
    ->javascriptIdentifierName
      ->javascriptReserved

HltTrace: javascriptReserved->Error
```

**Comment by othree** [comment]
Sorry I can't reproduce.
Could you provide a code snippets simple enough for this issue?

**Comment by dak0rn** [comment]
Sure.
It happens with the following code:

```javascript
const CONSTANT = 'CONSTANT';

const obj = {

    [ CONSTANT ](a) {
        return a * 3;
    },

    [ 'a' ]() {
        return 42;
    }

};
```

![code-red](https://cloud.githubusercontent.com/assets/3854533/13385473/7add99d8-dea1-11e5-8a25-013702decafc.png)

I also made sure no other plugin is running:

```
" :PluginList
Plugin 'othree/yajs.vim'
Plugin 'kergoth/vim-hilinks'
```

Versions:
- vim 7.4 on OS X
- yajs v1.5 (as of the changelog)

**Comment by othree** [comment]
Thanks, I thought this issue is in class~
