### ISSUE TITLE
missing syntax highlight

### ISSUE THREAD

**Issue by MikaAK** [othree/yajs.vim#121]
I just wanted to let you guys know of a few missing highlights I found. I don't use semicolons so that could be why this is occuring though it seems doubful. 
<img width="418" alt="screen shot 2016-03-09 at 2 32 43 am" src="https://cloud.githubusercontent.com/assets/4650931/13632604/5b41bbae-e59f-11e5-836e-208d19145e6f.png">
As you can see in the first `this` is highlighted but in the remaining it isn't. Finally also note that the arrow function params without braces isn't orange like the ones with braces.

Also noticed that `.method` is highlighted in template strings which is a bit weird
<img width="434" alt="screen shot 2016-03-10 at 10 50 27 am" src="https://cloud.githubusercontent.com/assets/4650931/13680554/eb8b45ea-e6ad-11e5-80f8-d398c4e34c8b.png">

**Comment by othree** [comment]
The second part is a not very clear to me.
Maybe I will need more lines of code to reproduce.

**Comment by MikaAK** [comment]
@othree thanks for the fix. The second part is with template strings where properties of an object are getting colored the same as the template string when it should be white.

**Comment by othree** [comment]
Do you use custom theme?
Because I can see they are in different color.

**Comment by MikaAK** [comment]
I do use [Molokai](https://github.com/tomasr/molokai). I've been customizing a lot of my syntax highlights though recently. What I've noticed is the second word in this case `amount` or `minDuration` are getting counted as `javascriptTemplateSubstitution > javascriptProp` while the first letter or `detail` is getting counted as `javascriptIdentifierName > javascriptIdentifierName`
