### ISSUE TITLE
Class properties support

### ISSUE THREAD

**Issue by k0kubun** [othree/yajs.vim#122]
```js
class Foo {
  static bar = {
    bar: bar,
  }

  static baz = {
    baz: baz,
  }
}
```

I use https://www.npmjs.com/package/babel-plugin-transform-class-properties to allow the syntax for class properties. yajs.vim regards the second `static` as invalid and highlights its background with red color.
It's valid for such a case and I want yajs.vim to support it. Can it be supported?

**Comment by othree** [comment]
Please use https://github.com/othree/es.next.syntax.vim

**Comment by k0kubun** [comment]
Works fine! Thank you for your nice works. :)
