### ISSUE TITLE
Arrow function highlighting is broken

### ISSUE THREAD

**Issue by mhinton** [othree/yajs.vim#123]
I have the latest version of this plugin and I am seeing broken highlighting of code before arrow functions.

You can see the broken highlighting on the 'describe' and 'it' lines.
![screenshot](https://cloud.githubusercontent.com/assets/23145/14180662/a6109128-f729-11e5-8df5-765cfac93a90.png)

**Comment by othree** [comment]
This issue caused by working together with https://github.com/othree/javascript-libraries-syntax.vim
Will try to fix.

**Comment by othree** [comment]
I have add an quick fix only for jasmine related global function.
Maybe you an take a look.

**Comment by mhinton** [comment]
That resolves this issue, thanks. 😃
