### ISSUE TITLE
Syntax highlighting breaks with unnamed class expression

### ISSUE THREAD

**Issue by patrkris** [othree/yajs.vim#124]
Hi

I've noticed that when I use a class expression the syntax highlighting breaks. Please see the attached images.

Not working:

![skaermbillede 2016-04-12 19 49 26](https://cloud.githubusercontent.com/assets/206189/14470062/d4dbcd66-00e7-11e6-88d6-40ac92817b86.png)

Working:

![skaermbillede 2016-04-12 19 49 17](https://cloud.githubusercontent.com/assets/206189/14470063/d4e05192-00e7-11e6-8e4a-5971cbe10e73.png)

-Patrick

**Comment by othree** [comment]
Fixed by https://github.com/othree/yajs.vim/commit/a679e3c8835ee68a1193bc832285710f0af5518f
