### ISSUE TITLE
export default function syntax highlighting is broken

### ISSUE THREAD

**Issue by FuzzOli87** [othree/yajs.vim#127]
![syntaxbroke](https://cloud.githubusercontent.com/assets/12246915/15057547/efef0396-12dc-11e6-88f9-423d7770a89c.png)

It seems the syntax coloring broke after the recent update.

**Comment by FuzzOli87** [comment]
I temporarily fixed it by adding javascriptFuncKeyword and javascriptAsyncFuncKeyWord to line 300. I'm not sure if this is the best way to do this (since asyncfunc stuff is from an optional plugin) but just a temp fix for people.

`syntax region  javascriptExportDef             start=/export/ end=/;\|\n/ contains=javascriptExport,javascriptExportDefault,javascriptFuncKeyword,javascriptAsyncFuncKeyWord,javascriptExportBlock,javascriptString,javascriptEndColons keepend`

**Comment by othree** [comment]
I decide to use simple syntax define for import and export.
Old solution is trying to avoid highlight `as` in other place.
