### ISSUE TITLE
Arrow functions after single quoted strings

### ISSUE THREAD

**Issue by nbeydoon** [othree/yajs.vim#129]
I have some troubles with syntax highlight with

```javascript

it('[WORD] a b c ...', () => {
    let a = 2;
    expect(a).to.equal(2);
});

```

Here all the variables inside the arrow functions are broken :/

**Comment by othree** [comment]
The semantic is correct, but the highlight link of `=>` is incorrect.
Just fixed, should looks like:

![2016-07-04 7 12 19](https://cloud.githubusercontent.com/assets/16474/16558860/4e5a19bc-421b-11e6-999b-4faf79d6a08b.png)

**Comment by nbeydoon** [comment]
I have this :/, I just have update all my plugings now.

![image](https://cloud.githubusercontent.com/assets/8340484/16559215/b9054eb0-41eb-11e6-8339-7f84f3490416.png)

**Comment by othree** [comment]
Could you provide a code snippets for this case?

**Comment by nbeydoon** [comment]
This snippet

```

describe('[foobartest]', () => {
    describe('test a route', () => {
        it('[CLIENT] should work', () => {
            let data = buildValidData();
            return data.save()
                .then(() => {
                    return request('put', `${data.pid}`)
                        .expect(200)
                        .expect(function (res) {
                            expect(res.body)
                                .to.be.an('object');
                        })
                });
        });
    })
});
```
<img width="491" alt="screen shot 2016-07-05 at 11 41 55" src="https://cloud.githubusercontent.com/assets/8340484/16580586/8116d8ba-42a5-11e6-953f-f79a645cacc7.png">

**Comment by othree** [comment]
I think it caused by other vim-script or setting
I have use yajs.vim and javascript-libraries-syntax with the setting

```vim
let g:used_javascript_libs = 'backbone,jquery,lodash,requirejs,jasmine'
```
Looks ok to me

![2016-07-11 11 02 57](https://cloud.githubusercontent.com/assets/16474/16718941/0e59ae5e-4757-11e6-9c7a-9b9819206334.png)

**Comment by othree** [comment]
I think the major problem is the word `it` highlighted in a different color.

**Comment by nbeydoon** [comment]
I have tried to put the `let g:used_javascript_libs = 'backbone,jquery,lodash,requirejs,jasmine'
` but this did nothing, but I am using your other module othree/es.next.syntax.vim maybe it is related ?

**Comment by othree** [comment]
I also use es.next.syntax.vim.
The line is for javascript-libraries-syntax.vim

    let g:used_javascript_libs = 'backbone,jquery,lodash,requirejs,jasmine'

If you dont know about this before.
This should not be the root cause.

I think you have a special syntax highlight definition affects this.
You can try cleanup `.vim` and `.vimrc` and enable stuffs one by one.

**Comment by nbeydoon** [comment]
Problem solved, I have clean my vimrc and it works. The problem is due to an other plugin syntax, thanks !
