### ISSUE TITLE
jspropertyname breaks indentation

### ISSUE THREAD

**Issue by bounceme** [othree/yajs.vim#130]
could you rename this to include `string` when it is written as a string ? that way property names with braces can not mess up indentation (search pair skip expressions notably)

**Comment by othree** [comment]
Do you mean `javascriptPropertyName` ?

Any sample code and how do you control indent?

**Comment by bounceme** [comment]
```
  (function() {
    console.log("value");
    var magicWords = ['abracadabra', 'gesundheit', 'ventrilo'],
      spells = {
        'f{{{{{{{ire}}}ball': function() {
          setOnFire()
        },
        'water': function() {
          putOut()
        }
      },
      a = 1,
      b = 'abc',
      etc;
    someFunc(param1, param2,
      param3, param4)
  }());
```
using this script:
https://github.com/pangloss/vim-javascript/blob/develop/indent/javascript.vim
also the matchparen/matchit plugins break.

**Comment by othree** [comment]
Fixed~

**Comment by bounceme** [comment]
great, thanks @othree !
