### ISSUE TITLE
{a(): => ({b: => {/* trouble here */}})}

### ISSUE THREAD

**Issue by yevhenpavliuk** [othree/yajs.vim#131]
When there's an arrow function with parenthesized object literal expression (i.e. the function returns an object):
```js
const object = {
    arrowFunctionReturningAnObject: () => ({
        arrowFunctionWithStatements: () => {
            return something;
        },
    }),
};
```
The result looks like as follows:
![issue](https://cloud.githubusercontent.com/assets/1070277/18452052/2e1d3fae-7942-11e6-9cdd-23bec014e3e2.png)
You can see that `arrowFunctionWithStatements` and `arrowFunctionReturningAnObject` are differently highlighted, although they're both object property names.
A statement inside `arrowFunctionWithStatements` is wrongly highlighted because of that.

**Comment by othree** [comment]
This is known issue.
Because I have to tell this from

    var func = () => () => () => true

Arrow function return arrow function.
And I didn't find any way to distinguish these two syntax.

**Comment by lohfu** [comment]
This is probably the same issue, code like this:

```
return fetch('/api/employees', {
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
})
  .then(response => response.json())
  .then(json => (
    // Test comment

    dispatch(employeesReceive(json.employees))
  ));

  //Normal comment
```

Looks like this

![2016-09-19-151611_427x240_scrot](https://cloud.githubusercontent.com/assets/7393351/18633352/2ee228c0-7e7c-11e6-8cfd-d1cfca687993.png)

**Comment by othree** [comment]
Yes, I think its the same issue

**Comment by othree** [comment]
Found a way to deal with arrow functions return `({})` directly

**Comment by othree** [comment]
@lohfu sorry I can't reproduce your issue
