### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by olalonde** [othree/yajs.vim#133]
I just updated my vim plugins with `:PluginUpdate` and am now getting incorrect indentation on some JavaScript files:

![sivcersgot](https://cloud.githubusercontent.com/assets/416585/19026689/949060cc-88dd-11e6-95de-d708f66fc5e9.gif)

I disabled all my plugins except for `yajs` and it seems the problem persists, so it is likely an issue with this plugin.

**Comment by othree** [comment]
I think this issue belongs to indent script, not syntax script

**Comment by olalonde** [comment]
Ah, ok... What's the indent script repo?

**Comment by othree** [comment]
Depends on which one you use, If you never choose one before.
You might use the one in the vim repo.

**Comment by olalonde** [comment]
Yes, all my plugins are disabled except `yajs`. Indentation works when I disable `yajs`, so yajs almost certainly has something to do with it. Can you reproduce? (disable all plugins except yajs and see if you get same indent as in the gif).

**Comment by olalonde** [comment]
Oh never mind, I have the same indentation even after disabling `yajs`. The indentation is however fixed by using `pangloss/vim-javascript` instead of `othree/yajs.vim`.

Indentation works:

```javascript
" Plugin 'othree/yajs.vim'
Plugin 'pangloss/vim-javascript'
```

Indentation doesn't work:

```javascript
Plugin 'othree/yajs.vim'
" Plugin 'pangloss/vim-javascript'
```

So I guess the question is (and I don't know viml well enough to answer), are syntax plugins supposed to hint vim about indentation? If not, do you know any plugin that will fix the indentation for javascript?

**Comment by olalonde** [comment]
Oh, this seems to be a related issue: https://github.com/othree/yajs.vim/issues/20

**Comment by othree** [comment]
I am using jiangmiao/simple-javascript-indenter
But its very old.
Not sure is it fit for no semicolon coding style
