### ISSUE TITLE
Support flow types?

### ISSUE THREAD

**Issue by radical-edo** [othree/yajs.vim#134]
Hi,

I'm currently your plugin to support JavaScript syntax and it's all great. But I've been thinking about using [flow](https://flowtype.org/) when writing my JS code. Understandably, this makes the syntax highlighting go nuts. ;(

It would be nice to have that support. Do you have plans on adding this sometime in the near future?

**Comment by othree** [comment]
This belongs to https://github.com/othree/es.next.syntax.vim/issues/6
