### ISSUE TITLE
Keywords are being highlighted when they are used as method names

### ISSUE THREAD

**Issue by marrs** [othree/yajs.vim#136]
Example snippet

``` Javascript
app.get('/*', (req, res) => res.status(404).end());
```

`.get` is being highlighted as a keyword (i.e. getter) even though it is not one in this context, as it is being called as a method instead.  Maybe adjust the regex to check if the word is preceded by a dot.

Bare in mind that, in Javascript, a dot can be separated from the method by whitespace or even a new line.

**Comment by othree** [comment]
Do you use javascript-libraries-syntax.vim ?
