### ISSUE TITLE
Incorrect group for javascript reversed words

### ISSUE THREAD

**Issue by chemzqm** [othree/yajs.vim#138]
I'm using `yajs.vim` and and `es.next.syntax.vim`
<img width="806" alt="screen shot 2016-12-06 at 1 38 52 pm" src="https://cloud.githubusercontent.com/assets/251450/20914291/9cc3b8b6-bbb9-11e6-9b14-98d73874d53d.png">
It works fine when I remove `{method = 'get', url, version = 1, controller, query = {}, data, headers}`

**Comment by chemzqm** [comment]
IMO, it doesn't make too much sense to highlight error by syntax highlight, it's hard to write and could cause performance issue easily, and the linters could be much better.

**Comment by othree** [comment]
Do you update to latest reversion?

**Comment by chemzqm** [comment]
@othree it works now, 👍  closed.
