### ISSUE TITLE
Wrong color for second if

### ISSUE THREAD

**Issue by Delapouite** [othree/yajs.vim#14]
```js
a.forEach(function() {
	if (true) {
	}
	if (true) {
	}
});
```
In this code example the second `if` is wrongly colored

**Comment by othree** [comment]
Hi
Do you use latest reversion from git repo.
I can't reproduce this issue.
Once have this issue is that if I use SyntaxRange.

**Comment by Delapouite** [comment]
Hi
Yes, I use the latest versin of yajs.vim.

To find what's happening, I installed this plugin : http://www.drchip.org/astronaut/vim/index.html#HILINKS . Everytime you move the cursor, it tells your which rules are under.

Here's the result for the first `if` : 

javascriptProp->javascriptFuncCallArg->javascriptBlock->javascriptConditional

And for the second one :

javascriptProp->javascriptFuncCallArg->javascriptReserved

**Comment by othree** [comment]
I found why the color is difference, but it hard to fix quick.
For unknown reason, syntax region nesting rule will be break if it contains=TOP

**Comment by othree** [comment]
Do you have complete code sample can provide?
I got `javascriptBlock->javascriptConditional` and `javascriptConditional` so my coloring is correct.
If I can known why you have `javascriptProp->javascriptFuncCallArg->` in the front.
Might be able to have a walk around to let it work.

**Comment by othree** [comment]
I think this is fixed.
Please take a try.
