### ISSUE TITLE
Proposal about changing highlighting of imports

### ISSUE THREAD

**Issue by k33nice** [othree/yajs.vim#143]
Hi!
What do you think about changing highlighting ```javascriptImport``` and ```javascriptExport```
as ```Include```. In other langs, I'm used to see imports higlighted as ```Include```?
So, for me, it's unusual, that it's have another highlighting.
I put this in my .vimrc
```vim
  au BufEnter *.js,*.jsx hi! link javascriptImport Include
  au BufEnter *.js,*.jsx hi! link javascriptExport Include
```
so it's no problem for me anymore. But maybe it would be more familar for other.

**Comment by othree** [comment]
I just try to find a good highlight group for import/export 2 days ago.
And `include` is in my blind spot
