### ISSUE TITLE
After hitting enter yajs never puts me at the right indentation level

### ISSUE THREAD

**Issue by ohjames** [othree/yajs.vim#145]
Lets say I type this:

`if (blah) {`

then after hitting enter I would expect to be indented inside of the if. But I'm not, I'm at the same level as the `if`. Weird. So now if I indent myself manually and type like this:

```javascript
if (blah) {
  call()
```

Then after hitting enter yajs indents me to the right of call() so if I start typing immediately I'll get:

```javascript
if (blah) {
  call()
    stuff()
```

Went back to vim-javascript.

**Comment by othree** [comment]
yajs.vim only do syntax highlight.
Indent is another story.
And yes, vim-javascript have indent support.

**Comment by ohjames** [comment]
Okay thanks for the info!
