### ISSUE TITLE
Nested Template Literals

### ISSUE THREAD

**Issue by woat** [othree/yajs.vim#146]
Currently, when nesting temp literals, the resulting highlighting is janky.

``` 
`<tag attr=${exp}>${exp}</tag>`
`${`<tag attr=${exp}>${exp}</tag>`}`
 ```

<img src="https://puu.sh/vS9oy/55d19a2268.png" height="50">

Ideally the top highlighting should be identical to the bottom when placed inside the expression.

What I assume is happening is the first \` gets matched to the second \`, when it should skip it (and match to the fourth \`) because it is inside the expression.

What it should look like would be similar to:

<img src="https://puu.sh/vS9wG/3c00a70d68.png" height="50">

**Comment by othree** [comment]
This is fixed now.
