### ISSUE TITLE
async/await not highlight

### ISSUE THREAD

**Issue by zhaochy1990** [othree/yajs.vim#152]
for async/await method in class, it works.
but for functions, it doesn't
![image](https://user-images.githubusercontent.com/10827209/34024577-ec65806e-e185-11e7-91b3-06d29c7a0330.png)

**Comment by othree** [comment]
Hi, this is what I see:

<img width="247" alt="2017-12-15 11 32 33" src="https://user-images.githubusercontent.com/16474/34025614-b8535f8e-e18b-11e7-91cd-3c2419ba9c0b.png">

I will need code snippets to reproduce your issue.

**Comment by jonashaag** [comment]
Not highlighted:
```js
foo()
(async () => ...)
```

Highlighted:
```js
foo();
(async () => ...)
```

Not highlighted:
```js
var spam = async function () {
}
```

**Comment by zhaochy1990** [comment]
maybe some other plugin has conflict with this. After I delete all other plugins, this works good. Maybe I should try to find which plugin conflict with this. Thanks for your quick response and hard work.
