### ISSUE TITLE
Closing bracket in template closes the containing block

### ISSUE THREAD

**Issue by kyrisu** [othree/yajs.vim#153]
This is better explained with an example:

```js
if (true) {
  let test1 = `123 }`;

  let test2 = '123';
}
```
The second variable declaration is not hightlighted properly because `}` in the template closed the `if` block.

**Comment by othree** [comment]
<img width="166" alt="2017-12-27 11 08 04" src="https://user-images.githubusercontent.com/16474/34369385-41956e7c-eaf6-11e7-9321-7951f3ee4c20.png">

Hi, works fine here.
Maybe its caused by other Vim script?
