### ISSUE TITLE
Vim colorscheme with good yajs.vim support

### ISSUE THREAD

**Issue by semanser** [othree/yajs.vim#154]
Hey. Is there any theme/colorscheme with good support of yajs? Currently, I am using [gruvbox](https://github.com/morhetz/gruvbox), but it doesn't support all of yajs syntax highlight groups.

**Comment by othree** [comment]
Hi, I am using jellybeans https://github.com/nanotech/jellybeans.vim
Every group in yajs.vim is link to a default group defined by Vim.
If you know which one is not defined in gruvbox.
Maybe you can give them suggestion or PR.
