### ISSUE TITLE
Arrow function syntax highlight error

### ISSUE THREAD

**Issue by henriquehirako** [othree/yajs.vim#156]
I'm writing unit tests with avajs, and the highlight is not quite working for arrow functions.
It just happens if I have this other arrow function call inside the test.

![image](https://user-images.githubusercontent.com/3274794/36149665-c164e930-10a7-11e8-82ae-d7a4d2ee13ef.png)

I'm using OceanicNext color scheme
```
henriquehirako:~/ $ vim -version                                                                                                                   [10:33:26]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  6 2018 20:43:24)
```

My dotfiles: http://github.com/henriquehirako/dotfiles

Thanks!

**Comment by othree** [comment]
This is a conflict by `Plugin 'crusoexia/vim-javascript-lib'` and yajs.

**Comment by othree** [comment]
I have add tape support to https://github.com/othree/javascript-libraries-syntax.vim .
You can switch to it for temp solution.
I will add avajs support later

**Comment by henriquehirako** [comment]
Awesome, thanks!!
