### ISSUE TITLE
Parenthesis Highlighting

### ISSUE THREAD

**Issue by signal-intrusion** [othree/yajs.vim#159]
I see lots of posts and screenshots with parens being highlighted in pairs. I cannot figure out the configuration to make that happen with yajs. Is there any documented configuration or options? How can I highlight parens? How are people achieving this?

What I see:
<img width="296" alt="screen shot 2018-02-19 at 4 50 03 pm" src="https://user-images.githubusercontent.com/5875587/36398410-fbc29cac-1594-11e8-9349-09c4dc576e91.png">

What other screenshots show:
<img width="347" alt="screen shot 2018-02-19 at 4 52 58 pm" src="https://user-images.githubusercontent.com/5875587/36398643-2439838e-1596-11e8-91c1-74d9fba49b05.png">
<img width="371" alt="screen shot 2018-02-19 at 4 51 30 pm" src="https://user-images.githubusercontent.com/5875587/36398644-2443ca7e-1596-11e8-8b1a-5c6425aefcbd.png">
<img width="432" alt="screen shot 2018-02-19 at 4 59 15 pm" src="https://user-images.githubusercontent.com/5875587/36398667-404af530-1596-11e8-8b91-7b3a7f873bd8.png">

**Comment by othree** [comment]
If nothing goes wrong, it depends on your color theme.
