### ISSUE TITLE
Another issue with the last update

### ISSUE THREAD

**Issue by ajkaanbal** [othree/yajs.vim#17]
Apparently occurs when an object property contains () or [] and a string.

![test2](https://cloud.githubusercontent.com/assets/800674/6272761/dda69e6e-b82f-11e4-90bd-9b3b2e408eb0.png)

```javascript
// Configurable paths for the application
  var appConfig = {
    app: require('./bower.json').appPath || 'app',
  };

  // Define the configuration for all the tasks
  grunt.initConfig({

    // Project settings
    yeoman: appConfig,

    // Watches files for changes and runs tasks based on the changed files
    watch: {
      bower: {
        files: ['bower.json'],
        tasks: ['wiredep']
      },
    }
    /// [....]
  });

```

**Comment by othree** [comment]
The last string cause this issue, use a not perfect solution now.
At least made other syntax looks correct.
Will try to fix the coloring of strings in object.

**Comment by ajkaanbal** [comment]
It works,  many thanks.
