### ISSUE TITLE
Logically inconsistent parameter coloring

### ISSUE THREAD

**Issue by izelnakri** [othree/yajs.vim#171]
Currently JavaScript parameters are considered 'Special' highlightGroup, however their references dont use the same color:

https://www.evernote.com/l/AL6gYm-zwiBJW4ZrvyLgn85G3rUi5nwFZlA

line 514 and line 515 should have the same color

**Comment by othree** [comment]
There is no way to understand the code only using Vim's syntax system.
So `user` at line 515 is recognized as an identifier. Not a parameter.

**Comment by othree** [comment]
I just know Bram is planing to add a new feature called text property.
Might possible to fix this issue in the future.
