### ISSUE TITLE
Highlight expressions in Template literals (Template strings) 

### ISSUE THREAD

**Issue by Endle** [othree/yajs.vim#173]
I'm not sure if this is caused by plugin conflict, but `othree/yajs.vim` failed to highlight template strings

Sample code
```
    let qBaseStr = `<div id="description">
                        <p>${q.Desc}</p>
                        <div id="hint">${multiHint}</div>
                    </div>`;

```

With no plugins (clean `.vim`)
![without](https://user-images.githubusercontent.com/3221521/50376015-a6bb2900-05d4-11e9-92b0-c94eead20f62.png)

`othree/yajs.vim`  is the only plugin installed
![withonly](https://user-images.githubusercontent.com/3221521/50376021-afabfa80-05d4-11e9-857b-bbc91675359d.png)

My vim's behaviour before `othree/yajs.vim` is installed
![before](https://user-images.githubusercontent.com/3221521/50376031-db2ee500-05d4-11e9-9273-49b9ac3025d5.png)

My vim's behaviour after `othree/yajs.vim` is installed
![with](https://user-images.githubusercontent.com/3221521/50376037-0a455680-05d5-11e9-9bea-e17e72547898.png)

The `${expression}` is really insignificant here. I wonder if this grammar is highlighted?

Thank you

<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals>

**Comment by othree** [comment]
Yes, inside the `${}`. Codes will highlight.
