### ISSUE TITLE
Arrow function seems not highlight correctly the inner block

### ISSUE THREAD

**Issue by lazywei** [othree/yajs.vim#19]
Hi, as title, the inner block of arrow function seems to be not correct.

For the first function (with old-style) in `then`, the return and the template string is highlighted correctly, while the last one (with arrow function) doesn't, please ref to the screenshot:

![image](https://cloud.githubusercontent.com/assets/2840571/6481007/7bbe46f6-c294-11e4-9456-ca65acffab1a.png)

**Comment by othree** [comment]
I can't reproduce this issue based on the given code block, could you provide code sample?

**Comment by lazywei** [comment]
How about this one?
https://gist.github.com/a0b119abd5074dde8f7c
When I open this file in my vim:

![image](https://cloud.githubusercontent.com/assets/2840571/6521066/59c9139a-c40c-11e4-8f0e-cf42e154d28f.png)

**Comment by othree** [comment]
Are you using latest reversion on github?

2015-03-06 14:23 GMT+08:00 Chih-Wei Chang <notifications@github.com>:

> How about this one?
> https://gist.github.com/a0b119abd5074dde8f7c
> When I open this file in my vim:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2840571/6521066/59c9139a-c40c-11e4-8f0e-cf42e154d28f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/19#issuecomment-77512928>.
>



-- 
OOO

**Comment by lazywei** [comment]
Oh, my local HEAD is 9dfb68c950ce22b9ef3155c5b613a80a1b2cfeac ... no wonder...
I confirmed this issue has been fixed after pulling the latest revision on GitHub.
Thanks!
