### ISSUE TITLE
Add to README -- differences from jelera/vim-javascript-syntax

### ISSUE THREAD

**Issue by davidosomething** [othree/yajs.vim#22]
Can you explain in the README the differences from latest jelera/vim-javascript-syntax ? Looks like this is more recent but the jelera version was last updated 2 months ago so I wouldn't consider it dead.

**Comment by othree** [comment]
I saw `jelera/vim-javascript-syntax` is not so active.
And I want to do lots of changes, including ES6 and other not confirmed standard support.
So I decide to maintain `yajs.vim` myself.

jelera's syntax is not dead.
I saw commits after I start this project.
I thinks his syntax file is simpler than mime, which means better performance.
One of my goal is to produce 100% right syntax.
But it hurt performance, so my goal is not complete now.
