### ISSUE TITLE
Support more exotic method names

### ISSUE THREAD

**Issue by maxnordlund** [othree/yajs.vim#23]
Since ES6 allows methods to be named to pretty much anything, like `return` or `throw`, it would be nice if yajs correctly highlighted this as method names, instead of marking it as a syntax error. The same goes for computed method names, e.g. `[Symbol.iterator]`. The latter seams to mess up the following return statement, which is sad.

For comparison it works as intended when highlighted as TypeScript, which is a superset of JavaScript.

   JavaScript   |   TypeScript
-------------------|-------------------
![JavaScript][] | ![TypeScript][]

[JavaScript]: https://cloud.githubusercontent.com/assets/664779/6986333/89626818-da3c-11e4-8aca-7b4e030f2f45.png
[TypeScript]: https://cloud.githubusercontent.com/assets/664779/6986389/0a4a3abe-da3d-11e4-9fc2-95395aca0fe4.png

```javascript
class Foo {
  constructor() {}

  throw(error) {}

  [Symbol.iterator](): Iterator {
    return this
  }

}
```

**Comment by othree** [comment]
Both issue were fixed, but you will need to remove the type annotation to check it.
Currently, type annotation is not under TC39's discussion.
So I will have no plan to support it right now.

I think type annotation will merge into JavaScript in one day.
But its still unclear when and how it looks like.

**Comment by maxnordlund** [comment]
Awesome, that's much nicer. Yes, I forgot to remove the annotations.
