### ISSUE TITLE
Typo in syntax/javascript.vim

### ISSUE THREAD

**Issue by HerringtonDarkholme** [othree/yajs.vim#24]
Dear othree, 

Thank you for your great syntax file. It's the most updated js syntax for vim. I really love it and am porting your syntax to typescript.

I found a typo here https://github.com/othree/yajs.vim/blob/master/syntax/javascript.vim#L272, where `javascriptClassBLock` should be `javascriptClassBlock`, a minor typo.

Thanks for your plugin!!

**Comment by othree** [comment]
Thanks
