### ISSUE TITLE
console method should not be exposed globally

### ISSUE THREAD

**Issue by HerringtonDarkholme** [othree/yajs.vim#25]
I think this is an issue in p.js and web-console.yml

In this picture, time is labelled as a consoleMethod, which has no proper `nextgroup`. And it introduces more highlighting problem.

![screenshot from 2015-04-09 21 12 36](https://cloud.githubusercontent.com/assets/2883231/7067853/e560a5ee-df00-11e4-9dc6-7bc89c1e9b26.png)

**Comment by othree** [comment]
Thanks, Console also match a pattern `/Cons/` I used to name Constructor.

**Comment by HerringtonDarkholme** [comment]
Looks Great :)
