### ISSUE TITLE
Support for npm like no semi colon coding style

### ISSUE THREAD

**Issue by mkoxio** [othree/yajs.vim#30]
http://mattbriggs.net/blog/2012/05/03/npm-style-javascript-is-the-conservative-choice/

**Comment by othree** [comment]
Could you provide some code sample to tell me current issue more clearly.
I don't think semicolon have any impact in current yajs.vim
It should work fine in this coding style.

**Comment by mkoxio** [comment]
Without semicolon:
![screen shot 2015-04-27 at 7 10 45 pm](https://cloud.githubusercontent.com/assets/10137567/7343222/d839a634-ed12-11e4-9051-90b38ae995a9.png)

With semicolon():
![screen shot 2015-04-27 at 7 12 47 pm](https://cloud.githubusercontent.com/assets/10137567/7343227/ebdbd2f2-ed12-11e4-8612-d6810257f8f2.png)

my .vimrc
https://gist.github.com/503dcec207a6053709eb

**Comment by othree** [comment]
Thanks, this is a regexp bug.

**Comment by mkoxio** [comment]
awesome!

**Comment by HerringtonDarkholme** [comment]
Though it rarely appears, ES6 spec does permits [StringLiteral in moduleSpecifier](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-imports), and StringLiteral does contain [multiline string](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-literals-string-literals)
