### ISSUE TITLE
Support method highlighting in Classes and short object syntax

### ISSUE THREAD

**Issue by damassi** [othree/yajs.vim#32]
These two images should suffice to explain:  

The first is highlighted:
![screen shot 2015-04-27 at 6 29 39 pm](https://cloud.githubusercontent.com/assets/236943/7361341/70f84676-ed0b-11e4-9edd-1df65bcb2375.png)

But the second is just white:
![screen shot 2015-04-27 at 6 29 51 pm](https://cloud.githubusercontent.com/assets/236943/7361343/7b2dcf80-ed0b-11e4-923a-d2d95e03f75c.png)

**Comment by othree** [comment]
Could you provide more complete sample code I can test ?
I am writing ES6 class too. But didn't see this.

**Comment by damassi** [comment]
Compare these three things, each of which should have the same exact method highlighting.  The latter two are different from the first, which correctly picks up on the function() keyword and highlights as should:  

```
var a = {
   hello: function() {},
   world: function() {}
}

var b = {
   hello() {},
   world() {}
}

class C extends Bar {
  hello() {}
  world() {}
}
```

**Comment by othree** [comment]
I thought method definition only available in class.
Let take a look the spec.

**Comment by othree** [comment]
You are right, fixing.

**Comment by othree** [comment]
Sorry I got the wrong point.
The coloring used now comes from function declaration.

    function ff() {}

Not easy to say what color is correct.
There is another case, method def with accessor:

    var b = {
       hello() {},
       set world() {},
    }

Do you have any idea of the color for `set`?
