### ISSUE TITLE
Support React.js / JSX-style template tags

### ISSUE THREAD

**Issue by damassi** [othree/yajs.vim#33]
Since JSX-style (React.js) components are quickly sweeping the industry (which is further supported by Facebook's relentless push towards ES6), it would be nice if yajs supported basic tag highlighting.  Currently all HTML tags are white.  

An image:
![screen shot 2015-04-27 at 6 36 34 pm](https://cloud.githubusercontent.com/assets/236943/7361393/5e3dc3ac-ed0c-11e4-9de2-902d84ed4da4.png)

**Comment by othree** [comment]
You could install https://github.com/mxw/vim-jsx
I already send PR but have some conflict
I will fix it later.

**Comment by damassi** [comment]
@othree - Unfortunately vim-jsx blows up yajs!  The two are not compatible.

**Comment by othree** [comment]
Could you try my [fork][1]
New PR is not accept, need wait for a while.

[1]:https://github.com/othree/vim-jsx

**Comment by damassi** [comment]
Nope!  Still breaks when using yajs.  It could be something with my setup, but I don't think so.

**Comment by othree** [comment]
Do you have sample code and screenshot
