### ISSUE TITLE
DocBlock comments are parsed incorrectly

### ISSUE THREAD

**Issue by damassi** [othree/yajs.vim#34]
See the image below.  Note the parens after `@param {ResponseModel} responseModel`, the white`*`, and so on.  

![screen shot 2015-05-07 at 1 06 43 pm](https://cloud.githubusercontent.com/assets/236943/7524930/2c4001ca-f4ba-11e4-8176-9197a198e3aa.png)

**Comment by othree** [comment]
Hi, I need sample code to debug.

**Comment by damassi** [comment]
Sure, try any comment:

```
  /**
   * Handler for preloading ideas when the Response form is first loaded.
   *
   * @param {Array} ids
   *    An array of Idea ids to load.
   */
```

**Comment by othree** [comment]
Thanks, this happened inside class block

**Comment by damassi** [comment]
Awesome, thank you!

**Comment by le0nik** [comment]
Doesn't work for me now:

![image](http://i.imgur.com/uX6g6lz.png)

```
/**
 * @public
 * @param {Object[]} changedOrderNumbers e.g. [{goodId: 1, shopOrderNumber: 32}, {goodId: 2, shopOrderNumber: 23}]
 * @returns {Promise}
 */
```
