### ISSUE TITLE
static method highlighted in red

### ISSUE THREAD

**Issue by sunjay** [othree/yajs.vim#36]
I don't believe my syntax here is wrong, but it is highlighted red. Is there any way to configure this or fix it?

Static methods: http://odetocode.com/blogs/scott/archive/2015/02/02/static-members-in-es6.aspx

![screenshot from 2015-05-14 11 51 00](https://cloud.githubusercontent.com/assets/530939/7635534/8cc5b04c-fa2f-11e4-9a35-7f556f4d53a6.png)

**Comment by othree** [comment]
I think there should not have `()` after `Test`

**Comment by sunjay** [comment]
@othree My mistake. I found the real problem. The red highlight appears when I use the "." in the extends.

![screenshot from 2015-05-15 11 32 45](https://cloud.githubusercontent.com/assets/530939/7656084/37efdaee-faf6-11e4-96c4-1917f7aad8c8.png)

![screenshot from 2015-05-15 11 34 02](https://cloud.githubusercontent.com/assets/530939/7656105/4f24dfe8-faf6-11e4-9712-97dec63cb8ff.png)

**Comment by othree** [comment]
I am not sure is dot valid there.
I will take a look.

2015-05-15 23:34 GMT+08:00 Sunjay Varma <notifications@github.com>:

> @othree <https://github.com/othree> My mistake. I found the real problem.
> The red highlight appears when I use the "." in the extends.
>
> [image: screenshot from 2015-05-15 11 32 45]
> <https://cloud.githubusercontent.com/assets/530939/7656084/37efdaee-faf6-11e4-96c4-1917f7aad8c8.png>
>
> [image: screenshot from 2015-05-15 11 34 02]
> <https://cloud.githubusercontent.com/assets/530939/7656105/4f24dfe8-faf6-11e4-9712-97dec63cb8ff.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/36#issuecomment-102433776>.
>



-- 
OOO

**Comment by sunjay** [comment]
It should be valid. [BabelJS](https://babeljs.io) understands it and it's pretty standard JavaScript syntax. I'm just accessing the OtherTest object in the test module.

**Comment by sunjay** [comment]
Also, even if that is invalid, `test.OtherTest` should be highlighted, not static.

**Comment by sunjay** [comment]
Did this get fixed?

**Comment by othree** [comment]
Yes, this fixed. but the title of this issue is not match so I didn't link it.

My reference is ecmascript draft.
And base on that. Not only `.` is acceptable.
All left hand side expression are ok to put there.

**Comment by sunjay** [comment]
Cool! I'm using vundle. How can I update so I get that fix?

Thanks for fixing it!

**Comment by othree** [comment]
I think bundle install! can update all plugins.
Or you can just go `.vim/bundle/yajs.vim` and git pull

2015-05-16 10:46 GMT+08:00 Sunjay Varma <notifications@github.com>:

> Cool! I'm using vundle. How can I update so I get that fix?
>
> Thanks for fixing it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/36#issuecomment-102566302>.
>



-- 
OOO

**Comment by sunjay** [comment]
Perfect! It works! Thank you!

Had to run `:PluginUpdate`
