### ISSUE TITLE
Consistent Parenthesis Highlighting

### ISSUE THREAD

**Issue by gf3** [othree/yajs.vim#38]
Hey, I'm trying to get consistent parenthesis highlighting unfortunately I'm running into some issues. Here's what the situation looks like:

![screen shot 2015-06-11 at 10 30 03 am](https://cloud.githubusercontent.com/assets/18397/8109593/89eee21a-1025-11e5-87bc-0cb9d0439b3f.png)

You'll notice that the parenthesis in the 2nd function and in the 3rd and 4th inner functions are not highlighting as `javascriptParens`. However if I try to highlight `javascriptFuncArg` as well it includes all the arguments, which is not what I want:

![screen shot 2015-06-11 at 10 39 37 am](https://cloud.githubusercontent.com/assets/18397/8109730/5a7f57ca-1026-11e5-9208-d8be87ffc775.png)

Any suggestions?

**Comment by othree** [comment]
The second image is what I expect.
The first line is not reasonable(but valid) because arrow function is always anonymous.
You will need assign it to a variable or use `()` to wrap it in order to use it.

**Comment by gf3** [comment]
All I'd like to be able to do is highlight arguments and parenthesis independently.

**Comment by othree** [comment]
Try uncomment line 291

    syntax match   javascriptParens                /[()]/

**Comment by gf3** [comment]
@othree That works great! Any chance on making that the default?

**Comment by othree** [comment]
The reason I comment this line out is because it might break nesting paren scope.
I can sure it works fine without this line.
But can't sure is it work correctly with this line.
And I don't have time to do a full test.
So I comment it out for now.

**Comment by othree** [comment]
https://github.com/othree/yajs.vim/commit/840fcb7d18c0ef075d0b76110f7a70c0becd4dd6#diff-af5b29be69c5b34c00e40f13b7e92435L296

I think this already in. (Accidentally)
Looks working fine.
