### ISSUE TITLE
Syntax highlighting on function parameters when adding line breaks.

### ISSUE THREAD

**Issue by jaredmcateer** [othree/yajs.vim#43]
The group I work with has a hard limit on line length and often in some angular controllers/apps we run a long list of dependencies we need to breakup the function parameters, unfortunately doing so break the syntax highlighting on them.

E.g.,
![foo_e](https://cloud.githubusercontent.com/assets/781540/8547378/ad0a78f8-247b-11e5-8c4b-3c6a185f7824.png)

![foo_c](https://cloud.githubusercontent.com/assets/781540/8547381/b412c074-247b-11e5-9406-3750234d8484.png)

**Comment by othree** [comment]
I plan to refactor this part. Since ES6 also support destructuring assignment here.
