### ISSUE TITLE
yajs.vim is screwing up my indenting

### ISSUE THREAD

**Issue by SirCmpwn** [othree/yajs.vim#44]
My vimrc can be found here: https://gogs.sr.ht/sircmpwn/dotfiles/src/master/vim/vimrc

When I have yajs installed and I open the following document:

    function foo(){
    };

Pressing `o` from the first line will not indent into the function body as expected.

**Comment by othree** [comment]
HI

I try your vimrc and install all the plugins.
But can't reproduce your issue.

**Comment by SirCmpwn** [comment]
[asciicast demonstrating the issue](https://asciinema.org/a/04l51cs751wzm4tnm5lshsrlc)

**Comment by othree** [comment]
I am using 748.
And It should indent for you.
I will try latest Vim.

**Comment by othree** [comment]
769 is ok here.
Would you possible to test on 7.4.769?

Not sure is OS affect this.
I am using OSX.

**Comment by SirCmpwn** [comment]
I'm on Linux, and I'm compiling 769 now to test with.

**Comment by SirCmpwn** [comment]
Problem is still present with 769.

**Comment by othree** [comment]
<https://gogs.sr.ht/sircmpwn/dotfiles/src/master/vim/vimrc#L96> Cause this.
I tested on ubuntu.
I think this only occurs on linux.
And not related to yajs (I try uninstall it and it still happens.)

**Comment by SirCmpwn** [comment]
Oh, I see. This must be the fault of my jsx plugin, then, rather than yajs. I'll report it to them, sorry to bother you.
