### ISSUE TITLE
Red highlight when returning class declaration

### ISSUE THREAD

**Issue by wordofchristian** [othree/yajs.vim#45]
I'm not sure if this is a problem with the syntax highlighter but when I return a class declaration from a factory function the keywords `class` and `extends` get red scary highlights.

<img width="319" alt="screenshot 2015-07-12 13 57 08" src="https://cloud.githubusercontent.com/assets/555044/8640028/59e27eba-289e-11e5-947d-4fac62e7f9cc.png">

The highlights go away when I return the class in a separate statement from declaration.

<img width="257" alt="screenshot 2015-07-12 13 57 38" src="https://cloud.githubusercontent.com/assets/555044/8640030/6ce0d4d0-289e-11e5-9bfb-5b15c3cf2fa2.png">

I don't see any syntactical reason why the first approach is incorrect. What do the red highlights mean exactly?

For reference my color scheme is https://github.com/w0ng/vim-hybrid

**Comment by othree** [comment]
I will take a look is this valid

**Comment by othree** [comment]
f2aeaa1b974345841bc06be6b37c7777512d584a
