### ISSUE TITLE
const, let and var keywords no longer highlighted

### ISSUE THREAD

**Issue by sunjay** [othree/yajs.vim#47]
Hi,
I ran PluginInstall to install some other plugins and I think yajs must have updated or something because several keywords are no longer highlighting at all.

Notice how `const`, `let` and `var` are not highlighted even though they are keywords.
![screenshot from 2015-07-14 11 24 52](https://cloud.githubusercontent.com/assets/530939/8677088/190517da-2a1b-11e5-8c00-1b4328e3ae78.png)

**Comment by othree** [comment]
Can't reproduce.
Maybe its caused by your theme color.

**Comment by othree** [comment]
No further information

**Comment by sunjay** [comment]
Yes. Sorry about that. This was due to my color scheme. You were right.
