### ISSUE TITLE
Regex Highlighting

### ISSUE THREAD

**Issue by Bipsy** [othree/yajs.vim#48]
Regular expressions are not being highlighted properly. I am using a regular expression that contains both the ' and ` characters. Currently it is intepreting the ` as the beginning of a template string. 

This is the regular expression that I am using. 
/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

Let me know if I can give any more information. Love this plugin by the way. The es6 support is superb.

**Comment by Bipsy** [comment]
/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

I apologize. The regex above was the actual expression. It have verified that it is legal. However, anything after the backtick is highlighted incorrectly.

**Comment by Bipsy** [comment]
The full expression is not being shown because part of it is being rendered as markdown. I'll try to figure out how to send the full expression.

**Comment by othree** [comment]
Use 4 space or ` to quote the expression?

**Comment by othree** [comment]
![2015-07-22 1 33 46](https://cloud.githubusercontent.com/assets/16474/8818608/4609026c-3076-11e5-8e68-44b665db6731.png)
Is this what you expect?

**Comment by Bipsy** [comment]
Yes, this is what I get.
<img width="1280" alt="screen shot 2015-07-21 at 11 38 24 pm" src="https://cloud.githubusercontent.com/assets/4576390/8818680/9e90f54a-3001-11e5-94c6-9d18c4955941.png">

**Comment by othree** [comment]
Do you update to latest reversion (just commit hours ago)?

**Comment by Bipsy** [comment]
I have not, but I'll do so now. Thank you for your quick response.

**Comment by Bipsy** [comment]
<img width="1280" alt="screen shot 2015-07-21 at 11 46 34 pm" src="https://cloud.githubusercontent.com/assets/4576390/8818780/c49a1860-3002-11e5-80de-f8afa7aae78c.png">

This is much better. However, the highlighting is still a little off. However, this is still major improvement. Thank you.

**Comment by othree** [comment]
Could you install thins plugin https://github.com/kergoth/vim-hilinks

And use `HLT` command to see the highlight trace before, between and after the white part?

**Comment by Bipsy** [comment]
The HLT command doesn't seem to do anything. Can you explain this more in depth?

**Comment by othree** [comment]
You can try another command `:HLT!` then move cursor and see statusbar

**Comment by Bipsy** [comment]
That worked.

Before: SynStack:  javascriptFuncCallArg->javascriptObjectLiteral->javascriptObjectLiteral->javascriptRegexpString->javascriptRegexpSet  HltTrace: T:javascriptRegexpSet->javascriptRegexpStr
ing->String->Constant fg<130> bg<-1>

During: SynStack:  javascriptFuncCallArg->javascriptObjectLiteral->javascriptObjectLiteral->javascriptRegexpString->javascriptRegexpSet  HltTrace: javascriptObjectLiteral             fg<-1>
 bg<-1>

After: SynStack:  javascriptFuncCallArg->javascriptObjectLiteral->javascriptObjectLiteral->javascriptRegexpString  HltTrace: javascriptRegexpString->String->Constant fg<130> bg<-1>

**Comment by othree** [comment]
Not sure why the first two have same SynStack but HltTrace is different.

**Comment by othree** [comment]
@Bipsy 
Is it ok to apply some change on your machine to see if bug fixed?
I can't reproduce your issue here.
