### ISSUE TITLE
Syntax folding

### ISSUE THREAD

**Issue by rosshadden** [othree/yajs.vim#49]
I am unfamiliar with how syntax folding is done, but I think `{\n,}`, `[\n,]`, and `(\n,)` would suffice to start (where `,` is a delimiter between open/close characters).

This was discussed a little in #20, but that issue is about something else (based on the title at least), so I'm breaking it out into its own issue.

Both [jelera/vim-javascript-syntax](https://github.com/jelera/vim-javascript-syntax) and [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) support syntax folding, so we can likely just use one of theirs.  Especially since this is a fork of the former :wink:.

**Comment by othree** [comment]
https://github.com/othree/yajs.vim/tree/fold

Only for some `{`. I have try fold everything listed above, but its not useful.

**Comment by rosshadden** [comment]
Thanks for working on this!  It seems to only work on functions.  It doesn't collapse arbitrary `{`s, like in for loops, if statements, es6 class functions, etc.  I think if it collapsed all `{`s it would handle every case.

I don't know if this is trivial or not, sorry for assuming I know how it works... haha.

**Comment by othree** [comment]
I can add support all `{` but it will cause too much fold.
And become not useful.
If you want to try I will make another commit.

**Comment by rosshadden** [comment]
If it's not too much trouble, I would appreciate that.  Syntax folds are typically done manually, so you only fold where you want to.  Thus I don't see a reason why it wouldn't be desired to fold on every `{` (and `[` and `(` for that matter, but I'll pick my battles).

**Comment by othree** [comment]
When I set foldmethod=syntax
All brackets will auto fold.
That's why I think its not useful.
What is your setting about syntax fold.

**Comment by rosshadden** [comment]
```

**Comment by rosshadden** [comment]
```

**Comment by rosshadden** [comment]
```
set foldmethod=syntax
set foldlevelstart=128
set foldcolumn=0
```

The fold function included in [vim-javascript-syntax](https://github.com/jelera/vim-javascript-syntax) must have had the same side-effect that you describe, right?  Which would mean people are used to it.  Also have you tried just using theirs verbatim, or is it not that straightforward?

**Comment by rosshadden** [comment]
Ah, the folding in `vim-javascript-syntax` is opt-in, so people don't notice it unless they run `JavaScriptFold()`.  I think doing this here would satisfy people that want folding without messing up people that don't.

They recommend people run it automatically, of course, but since it's not the default behavior it's non-intrusive.
```
au FileType javascript call JavaScriptFold()
```

**Comment by gavocanov** [comment]
I also noticed that folding is not OK, not in this plugin and vim-javascript-syntax, it works only with https://github.com/pangloss/vim-javascript

**Comment by othree** [comment]
I think vim-javascript-syntax fold every `{` `}`.

They use the following setting:

	setl foldmethod=syntax
	setl foldlevelstart=1

But I think the setting should set by users who know what it means.
I will update fold branch to support fold every `{` `}` later.
For the settings. I will leave on README only.

**Comment by JoshMock** [comment]
I would also love an optional folding option similar to `JavaScriptFold`. Even if it's not perfect, it's better than no syntax folding at all. And if it's off by default nobody gets hurt unless they want to be. :)

**Comment by faceleg** [comment]
I too would like the option to opt-in to some automatic folding configuration for JS

**Comment by romgrk** [comment]
I do not know if this is worked on/active, but this setup seems to work correctly.
```diff
diff --git a/syntax/javascript.vim b/syntax/javascript.vim
index a5d83dd..faf3d88 100644
--- a/syntax/javascript.vim
+++ b/syntax/javascript.vim
@@ -77,7 +77,7 @@ syntax match   javascriptOpSymbol              contained /\(\^\|\~\)/
 "JavaScript comments
 syntax keyword javascriptCommentTodo           contained TODO FIXME XXX TBD
 syntax region  javascriptLineComment           start="//" end="\n" contains=@Spell,javascriptCommentTodo 
-syntax region  javascriptComment               start="/\*"  end="\*/" contains=@Spell,javascriptCommentTodo extend
+syntax region  javascriptComment               start="/\*"  end="\*/" contains=@Spell,javascriptCommentTodo extend fold
 syntax cluster javascriptComments              contains=javascriptDocComment,javascriptComment,javascriptLineComment
 
 "JSDoc
@@ -231,7 +231,7 @@ syntax keyword javascriptExceptions            catch throw finally
 syntax keyword javascriptDebugger              debugger
 
 syntax region  javascriptSwitchExp             contained start=/(/ end=/)/ matchgroup=javascriptParens contains=javascriptFuncKeyword,javascriptComma,javascriptDefaultAssign,@javascriptComments nextgroup=javascriptSwitchBlock skipwhite skipwhite skipempty
-syntax region  javascriptSwitchBlock           matchgroup=javascriptBraces start=/\([\^:]\s\*\)\=\zs{/ end=/}/ contains=javascriptCaseColon,javascriptCaseRegion,@htmlJavaScript
+syntax region  javascriptSwitchBlock           matchgroup=javascriptBraces start=/\([\^:]\s\*\)\=\zs{/ end=/}/ contains=javascriptCaseColon,javascriptCaseRegion,@htmlJavaScript fold
 syntax region  javascriptCaseRegion            contained start=/case/ end=/:/ contains=javascriptCase,@javascriptExpression nextgroup=javascriptBlock skipwhite skipempty
 syntax match   javascriptCaseColon             contained /:/ nextgroup=javascriptBlock skipwhite skipempty
 
@@ -289,7 +289,7 @@ syntax keyword javascriptExport                export nextgroup=javascriptExport
 syntax keyword javascriptExport                module
 syntax keyword javascriptExportDefault         contained default
 
-syntax region  javascriptBlock                 matchgroup=javascriptBraces start=/\([\^:]\s\*\)\=\zs{/ end=/}/ contains=@htmlJavaScript
+syntax region  javascriptBlock                 matchgroup=javascriptBraces start=/\([\^:]\s\*\)\=\zs{/ end=/}/ contains=@htmlJavaScript fold
 
 syntax match   javascriptObjectMethodName      contained /[a-zA-Z_$]\k*\ze\_s*(/ nextgroup=javascriptFuncArg skipwhite skipempty
 syntax cluster javascriptObjectMethod          contains=javascriptMethodAccessor,javascriptObjectMethodName
@@ -315,7 +315,7 @@ syntax keyword javascriptClassSuper            super
 syntax match   javascriptClassName             contained /\k\+/ nextgroup=javascriptClassBlock,javascriptClassExtends skipwhite
 syntax match   javascriptClassSuperName        contained /[a-zA-Z_$][a-zA-Z_$\[\]\.]*/ nextgroup=javascriptClassBlock skipwhite
 syntax keyword javascriptClassExtends          contained extends nextgroup=javascriptClassSuperName skipwhite
-syntax region  javascriptClassBlock            contained matchgroup=javascriptBraces start=/{/ end=/}/ contains=javascriptMethodName,javascriptMethodAccessor,javascriptClassStatic,@javascriptComments
+syntax region  javascriptClassBlock            contained matchgroup=javascriptBraces start=/{/ end=/}/ contains=javascriptMethodName,javascriptMethodAccessor,javascriptClassStatic,@javascriptComments fold
 syntax keyword javascriptClassStatic           contained static nextgroup=javascriptMethodName,javascriptMethodAccessor skipwhite
 
 
@@ -325,7 +325,7 @@ syntax keyword javascriptOfComprehension       contained of
 syntax keyword javascriptIfComprehension       contained if nextgroup=javascriptIfComprehensionTail
 syntax region  javascriptIfComprehensionTail   contained matchgroup=javascriptParens start=/(/ end=/)/ contains=javascriptExpression nextgroup=javascriptForComprehension,javascriptIfComprehension skipwhite skipempty
 
-syntax region  javascriptObjectLiteral         contained matchgroup=javascriptBraces start=/{/ end=/}/ contains=@javascriptComments,javascriptObjectLabel,javascriptComma,@javascriptObjectMethod,javascriptPropertyName,javascriptComputedPropertyName,@javascriptValue
+syntax region  javascriptObjectLiteral         contained matchgroup=javascriptBraces start=/{/ end=/}/ contains=@javascriptComments,javascriptObjectLabel,javascriptComma,@javascriptObjectMethod,javascriptPropertyName,javascriptComputedPropertyName,@javascriptValue fold
 
 " syntax match   javascriptBraces                /[\[\]]/
 syntax match   javascriptParens                /[()]/
```

**Comment by othree** [comment]
@romgrk Thank you.
Some code already changed so I merged it manually.

**Comment by romgrk** [comment]
All gut. I was also wondering if there is some sort of documentation regarding `jsDoc` comments and other things like that? 
Also, is there a way to quickly toggle highlighting of browser-related keywords?
More generally, WHERE IS THE DOC?
(But thanks anyway for all this, any vim-plugin is hard enough to maintain to be awarded our eternal gratitude)
