### ISSUE TITLE
Decorators, class properties

### ISSUE THREAD

**Issue by bmcorser** [othree/yajs.vim#50]
I see this:
<img width="509" alt="screen shot 2015-07-25 at 19 48 40" src="https://cloud.githubusercontent.com/assets/1449387/8890816/6215fe28-3306-11e5-858e-94fa89f2ca10.png">

It looks like the opening  `'` isn't seen as a delimiter?

**Comment by bmcorser** [comment]
Decorators don't appear to be supported (apologies if this is syntastic or something else!). I've made a little screen cap showing this and the original issue
![es6](https://cloud.githubusercontent.com/assets/1449387/8890838/99867e18-3307-11e5-9dba-1736a95401c6.gif)

**Comment by othree** [comment]
I missed this syntax (class default property)
Will figure out late.

**Comment by othree** [comment]
@bmcorser base on latest ES6 draft.
I don't think this is valid class syntax.
Even if babel support this kind of syntax.

**Comment by othree** [comment]
Decorator is not in todo list now.
I don't want include future stuff in here.
But might have another project to add future spec support.

**Comment by bmcorser** [comment]
@othree Can you link to the appropriate part of the ES6 docs where you read about class default properties? I'm assuming the "proper" way to do it would be something like:
``` javascript
class Thing{
  constructor () {
    this.defaultProperty = 'abc';
  }
}
```
However, that would rely on developers (as far as I understand ES6 classes) faithfully calling `super` on subclass constructors. But that's not our problem `:)`

Fair enough on decorator syntax; that's your discretion.

**Comment by othree** [comment]
ref: http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#april_14_2015_rev_38_final_draft

14.5 Class Definitions

    ClassDeclaration[Yield, Default] :
        class BindingIdentifier[?Yield] ClassTail[?Yield] 
        [+Default] class ClassTail[?Yield]
    
    ClassTail[Yield] :
        ClassHeritage[?Yield]opt {ClassBody[?Yield]opt}

    ClassBody[Yield] : 
        ClassElementList[?Yield]

    ClassElementList[Yield] : 
        ClassElement[?Yield]
        ClassElementList[?Yield] ClassElement[?Yield]

    ClassElement[Yield] : 
        MethodDefinition[?Yield]

14.3 Method Definitions Syntax

    MethodDefinition[Yield] :
        PropertyName[?Yield] (StrictFormalParameters) {FunctionBody} 
        GeneratorMethod[?Yield]
        get PropertyName[?Yield] ( ) { FunctionBody }
        set PropertyName[?Yield] ( PropertySetParameterList ) { FunctionBody }

**Comment by othree** [comment]
The proper way you assume is correct as I know.

For future spec, my base line is appear in spec.
I think create another project to do the future spec support is a good way to keep yajs stable.
Maybe I will start soon for type and decorator.

**Comment by bmcorser** [comment]
That's great. I'll pass on to [where it was](https://github.com/aurelia/skeleton-navigation/blob/master/src/users.js) I got that syntax from.

Closing this :+1:

**Comment by othree** [comment]
https://github.com/othree/es.next.syntax.vim

**Comment by othree** [comment]
I found the proposal of class property initializer  
<https://gist.github.com/jeffmo/054df782c05639da2adb>

Will move to es.next.syntax

**Comment by bmcorser** [comment]
Nice one. It seems pretty early in the development; they are calling it __Stage 0__

**Comment by bmcorser** [comment]
__Stage 0__ is called "Strawman", it has no criteria for inclusion so not sure what the likelihood of it going in is ...

**Comment by bmcorser** [comment]
https://docs.google.com/document/d/1QbEE0BsO4lvl7NFTn5WXWeiEIBfaVUF7Dk0hpPpPDzU/edit

**Comment by othree** [comment]
Thanks, I know the TC39 process.
My idea is if there is a transpiler supports the new syntax.
And if this syntax might in of ES.Next.
I will try support it in es.next.syntax.vim.

If it comes to stage 3 or browsers are start to support it.
I will move it to yajs.vim.
