### ISSUE TITLE
Escaped newlines cause issues

### ISSUE THREAD

**Issue by bfrog** [othree/yajs.vim#53]
I noticed when quotes with escaped new lines,  while valid ecmascript, seems to give the syntax highlighter issues such that it doesn't recognized the stuff in between quotes as a string and it fails to find the escape quote.

Example of problematic javascript...

``` javascript
var mybigstring = "the world \
is a wonderful place \
where all the highlighters \
work without disgrace!";
```

**Comment by othree** [comment]
This syntax should be supported.
I will take a look.

**Comment by bfrog** [comment]
I looked a little closer, it seems like when the string line is a certain length I get an issue, screen shot
![screenshot from 2015-08-19 08-31-58](https://cloud.githubusercontent.com/assets/135839/9357472/cb8abe08-464c-11e5-8e2a-03fc4909b6ee.png)

**Comment by othree** [comment]
Try set `synmaxcol` option to larger number.

**Comment by bfrog** [comment]
that fixes it, thanks!
