### ISSUE TITLE
Syntax porblem with other plugin

### ISSUE THREAD

**Issue by linlinlinlin** [othree/yajs.vim#54]
When I set vim plugin with
```
Plugin 'othree/javascript-libraries-syntax.vim'
```
The result of sample code:
![before](https://cloud.githubusercontent.com/assets/8558312/9463063/a4760eb2-4b4c-11e5-89d2-f1eb170ee6e2.png)

When I set vim plugin with
```
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'othree/yajs.vim'
```
![after](https://cloud.githubusercontent.com/assets/8558312/9463070/b3cf7bbe-4b4c-11e5-8367-8716d8193c20.PNG)

Syntax highlight getting wired.

**Comment by othree** [comment]
Thanks, this is a regexp string pattern bug.
