### ISSUE TITLE
Regular highlighting within interpolation

### ISSUE THREAD

**Issue by srushti** [othree/yajs.vim#57]
I was wondering if it would be possible for the code inside an ES6 interpolation highlighted like normal code. The default Ruby syntax highlighting has an example of this https://github.com/b4winckler/macvim/blob/master/runtime/syntax/ruby.vim.

I have no idea if that is significantly difficult, so it might not be feasible, but it would be great.

Ruby highlighting:
<img width="413" alt="ruby interpolation" src="https://cloud.githubusercontent.com/assets/52381/9595748/d3447c86-50ad-11e5-9b7c-506809786a5a.png">

YAJS highlighting:
<img width="409" alt="yajs interpolation" src="https://cloud.githubusercontent.com/assets/52381/9595751/e2f68dd6-50ad-11e5-8c11-36e1fa353fb6.png">

Regardless of the outcome of this, thanks for building this.

**Comment by othree** [comment]
Its possible but I am not sure is it good.
It might be confuse people.

**Comment by srushti** [comment]
I'm sure it's subjective, but for my part having worked on Ruby for 4-5 years, I loved having that functionality, and it never confused me. An argument could also be made for keeping it consistent with the default highlighting in other languages. But like I said, it's subjective.

**Comment by simonratner** [comment]
You have my vote, sir: :+1:

**Comment by simonratner** [comment]
If you are curious to try it:
```diff
diff --git a/syntax/javascript.vim b/syntax/javascript.vim
index 5849360..e0b0e49 100644
--- a/syntax/javascript.vim
+++ b/syntax/javascript.vim
@@ -152,12 +152,9 @@ syntax cluster javascriptStatement             contains=javascriptBlock,javascri

 "Syntax in the JavaScript code
 " syntax match   javascriptASCII                 contained /\\\d\d\d/
-syntax region  javascriptTemplateSubstitution  contained matchgroup=javascriptTemplateSB start=/\${/ end=/}/ contains=javascriptTemplateSBlock,javascriptTemplateSString
-syntax region  javascriptTemplateSBlock        contained start=/{/ end=/}/ contains=javascriptTemplateSBlock,javascriptTemplateSString transparent
-syntax region  javascriptTemplateSString       contained start=/\z(["']\)/  skip=/\\\\\|\\\z1\|\\\n/  end=/\z1\|$/ extend contains=javascriptTemplateSStringRB transparent
-syntax match   javascriptTemplateSStringRB     /}/ contained
 syntax region  javascriptString                start=/\z(["']\)/  skip=/\\\\\|\\\z1\|\\\n/  end=/\z1\|$/ nextgroup=@javascriptComments,@javascriptSymbols skipwhite skipempty
 syntax region  javascriptTemplate              start=/`/  skip=/\\\\\|\\`\|\n/  end=/`\|$/ contains=javascriptTemplateSubstitution nextgroup=@javascriptComments,@javascriptSymbols skipwhite skipempty
+syntax region  javascriptTemplateSubstitution  matchgroup=javascriptBraces start=/\${\@=/ end="" contained nextgroup=@javascriptExpression
 " syntax match   javascriptTemplateTag           /\k\+/ nextgroup=javascriptTemplate
 syntax region  javascriptArray                 matchgroup=javascriptBraces start=/\[/ end=/]/ contains=@javascriptValue,javascriptForComprehension,@javascriptComments nextgroup=@javascriptComments,@javascriptSymbols skipwhite skipempty
```
(No guarantees, I hacked this up in a couple of minutes.)

**Comment by othree** [comment]
I thins that should use `contains=@javascriptExpression` not nextgroup

**Comment by simonratner** [comment]
I thought so too, but couldn't get it to work that way.

**Comment by othree** [comment]
Ha, I see why now. Your region is not based on my region.
You can try

    syntax region  javascriptTemplateSubstitution  contained matchgroup=javascriptTemplateSB start=/\${/ end=/}/ contains=@javascriptExpression

Don't test yet

**Comment by Vekat** [comment]
I also think this would be a nice feature.
