### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by bdryanovski** [othree/yajs.vim#58]
![screen shot 2015-09-07 at 11 13 45](https://cloud.githubusercontent.com/assets/204564/9712393/fe4f57f8-5552-11e5-9c49-5b679c165f5f.png)

I found that when there is es6 string interpolation. The syntax highlight is broken. I try to find a solution to this - but at this point in time - did not have much of success. 

So could someone give a hand? ;)

**Comment by othree** [comment]
Can't reproduce.
Please provide code snippets.

2015-09-07 16:26 GMT+08:00 Bozhidar Dryanovski <notifications@github.com>:

> [image: screen shot 2015-09-07 at 11 13 45]
> <https://cloud.githubusercontent.com/assets/204564/9712393/fe4f57f8-5552-11e5-9c49-5b679c165f5f.png>
>
> I found that when there is es6 string interpolation. The syntax highlight
> is broken. I try to find a solution to this - but at this point in time -
> did not have much of success.
>
> So could someone give a hand? ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/58>.
>



-- 
OOO

**Comment by othree** [comment]
Is this still happen?

**Comment by bdryanovski** [comment]
Sorry for the late reply, I didn't notice the notification. Yep it's still a issue.

![screen shot 2015-09-16 at 16 54 47](https://cloud.githubusercontent.com/assets/204564/9906658/d7477332-5c93-11e5-9754-c22bf640f451.png)

```javascript
    if (option.method === 'POST') {
      let body = ''
      Object.keys(params).forEach((key) =>
        let value = params[key]
        if (typeof value !== 'string') {
          value = JSON.stringify(value)
        }
        if (value !== undefined) {
          body += `${ encodeURIComponent(key) }=${ encodeURIComponent(value) }&`
        }
      )
      options.body = body
    } else {
      // ... more code
    }
```

You could find my Vim setup here: https://github.com/bdryanovski/vimrc

**Comment by othree** [comment]
Hi the code is not valid, you missed `{}` after `=>`
Its required if your function is multiline

```js
if (option.method === 'POST') {
  let body = ''
  Object.keys(params).forEach((key) => {
    let value = params[key]
    if (typeof value !== 'string') {
      value = JSON.stringify(value)
    }
    if (value !== undefined) {
      body += `${ encodeURIComponent(key) }=${ encodeURIComponent(value) }&`
    }
  })
  options.body = body
} else {
  // ... more code
}
```

**Comment by bdryanovski** [comment]
Yep, the code have a syntax error ;)
But still the issue is there even when replacing it with `function` for example here:
![screen shot 2015-09-17 at 10 50 35](https://cloud.githubusercontent.com/assets/204564/9927795/16f7a20e-5d2a-11e5-83f9-ed72b63426e2.png)

```javascript
  if (option.method === 'POST') {
      let body = ''
      Object.keys(params).forEach(function(key) {
          let value = params[key]
          if (typeof value !== 'string') {
            value = JSON.stringify(value)
          }
          if (value !== undefined) {
            body += `${ encodeURIComponent(key) }=${ encodeURIComponent(value) }&`
          }
      })
      options.body = body
    } else {
      Object.keys(params).forEach(function(key) {

          let value = params[key]
          if (typeof value !== 'string') {
            value = JSON.stringify(value)
          }
          options.uri += `${ encodeURIComponent(key) }=${ encodeURIComponent(value) }&`
      })
    }

    if (options.body === undefined || options.body === '') {
      delete options.body
    }

    return new Promise(function(resolve, reject) {
        request(options, function(error, response, body) {
            let json = ''
            if (error !== null) {
              return reject({ error: error })
            }
            try {
              json = JSON.parse(body)
              if (json !== null && json.error !== undefined) {
                return reject(json)
              }
            } catch(e) {
              json = { error: { code: 'JSONPARSE', error: e } }
              return reject(json)
            }
            return resolve(json)
        })
    })
```

I think that the count for closing the string is sometimes wrong. I found this issue into working library so the code is not that important for example here: 

![screen shot 2015-09-17 at 10 56 54](https://cloud.githubusercontent.com/assets/204564/9927897/dbf7f59a-5d2a-11e5-9bf9-2b81c929a84b.png)

and here is the code:  https://github.com/jmdobry/CacheFactory/blob/master/src/index.js#L85
It could be some kind of plugin conflict ? But I have hard time locating it. So if you have some hints I will be happy to help

**Comment by othree** [comment]
![2015-09-17 4 07 19](https://cloud.githubusercontent.com/assets/16474/9928102/34bcf52e-5d56-11e5-9b6e-be14fb45958a.png)

Here is ok, maybe its a conflict with other plugins

**Comment by bdryanovski** [comment]
hmz .. may be .. I will check this and write back
