### ISSUE TITLE
Highlighting of comments after import

### ISSUE THREAD

**Issue by mikekreeki** [othree/yajs.vim#59]
Looks like comment highlighting does not when used after import definition (on the same line) or between import definitions (on a separate line). 

Example code:

```js
import foo from 'bar' // this comment is not highlighted (matched as jsImportContainer)
import bar from 'xyz'
// this comment is also not highlighted 
import xyz from 'foo'

// this one is highlighted correctly
```

It sometimes looks funny since other parts of the comment might get accidentally highlighted, like in this real world example:

![](https://dl.dropboxusercontent.com/u/6573004/Screenshot%202015-09-09%2015.54.34.png)

Here words _import_ and _default_ are part of the comment but are highlighted the same as keywords.

**Comment by othree** [comment]
Not sure what happened. It works fine here.

![2015-09-10 11 15 09](https://cloud.githubusercontent.com/assets/16474/9779317/50827ddc-57ad-11e5-90b8-e4653aa87fda.png)

**Comment by mikekreeki** [comment]
It turned out removing `jelera/vim-javascript-syntax` from my `~/.vimrc` fixes the issue. So is `yajs.vim` a full replacement for `jelera/vim-javascript-syntax`?

**Comment by othree** [comment]
Yes, yajs is full JS syntax

**Comment by mikekreeki** [comment]
Very cool, thank you very much for your effort :wink:
