### ISSUE TITLE
javascriptGlobal, javascriptMessage should be removed from javascript.vim

### ISSUE THREAD

**Issue by simonratner** [othree/yajs.vim#62]
The keywords they define are not standard js, and they are in `syntax/yajs/web-window.vim` anyway, which is where they belong. Looks like they might be left over from some old code?

**Comment by othree** [comment]
If you are willing to help test.
I start to refactor this part in `webidl` branch.

<https://github.com/othree/yajs.vim/tree/webidl>

**Comment by simonratner** [comment]
I will try out that branch, thanks.
