### ISSUE TITLE
Function call as a default argument in a method parameter messes up syntax highlight

### ISSUE THREAD

**Issue by susu** [othree/yajs.vim#65]
When there is a default argument in a class' method parameter that is a function call, it messes up the method's syntax highlighting.

Please see the attached screenshot, which probably worth more than words. See ``myfun and myotherfun``:

![screenshot](https://cloud.githubusercontent.com/assets/934382/9876512/f0147726-5bb6-11e5-8574-f425450b2660.png)

(PS. I use colorscheme=pablo)
(Here is a gist of the test code: https://gist.github.com/susu/9df08e0dd34688eaff09)

**Comment by othree** [comment]
In fact, current version don't support default value. >_<

**Comment by othree** [comment]
Sorry for previous comment is not correct. This is a bug.

**Comment by susu** [comment]
I confirm, it's fixed.
Thank you for your quick response and fix!
