### ISSUE TITLE
Highlights keywords as error in anoymous blocks.

### ISSUE THREAD

**Issue by rhys-vdw** [othree/yajs.vim#69]
![screen shot 2015-09-30 at 5 43 49 pm](https://cloud.githubusercontent.com/assets/822105/10187308/de965236-679a-11e5-91e7-3a88290b0d96.png)

Highlights scoped `const` and `return` keywords in anonymous blocks. Maybe it thinks these are objects literals?

**Comment by othree** [comment]
https://github.com/othree/yajs.vim/commit/7f7a3095d5de373ceb936dbc9dcb142f394b4be9
