### ISSUE TITLE
JSX highlight issue with vim-jsx

### ISSUE THREAD

**Issue by jmarceli** [othree/yajs.vim#70]
For .jsx code I get (I think) buggy highlighting: 
![image](https://cloud.githubusercontent.com/assets/4281333/10189903/6662b812-6769-11e5-81b4-77acd3344b14.png)

It is fixed once I add space in ending tag after `<`. It's not mayor issue but I think that `<a></a>` should be considered correct notation as well as `<a></ a>`.

It doesn't get better even if I enable [vim-jsx](https://github.com/mxw/vim-jsx) plugin.
Anyway great plugin.

**Comment by othree** [comment]
![2015-09-30 5 56 57](https://cloud.githubusercontent.com/assets/16474/10190071/b0bf5b08-679c-11e5-8420-16d6bc90813f.png)

This is what I see if I use vim-jsx.
Is it looks the same?

**Comment by jmarceli** [comment]
Sorry for the trouble. Everything starts to work correctly when I reopen the files. My screen was taken after `source ~/.vimrc` command (I thought that it will just work).

Anyway thanks for instant support :)
