### ISSUE TITLE
Async/await syntax highlighting

### ISSUE THREAD

**Issue by dan-silva** [othree/yajs.vim#73]
I see that these keywords were removed from the syntax definitions. Was there any reason for dropping them?

**Comment by othree** [comment]
I move es7 features to another repo~

https://github.com/othree/es.next.syntax.vim

**Comment by dan-silva** [comment]
Hmm got it. Maybe it would be nice to reference this the es.next repo in the README, so other people can use it.

**Comment by othree** [comment]
Your're right.
Too busy to factor every changes into document.

2015-10-05 1:13 GMT+08:00 Daniel Santana <notifications@github.com>:

> Hmm got it. Maybe it would be nice to reference this the es.next repo in
> the README, so other people can use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/73#issuecomment-145367274>.
>



-- 
OOO

**Comment by othree** [comment]
Information added.
