### ISSUE TITLE
`new` incorrectly highlighted red

### ISSUE THREAD

**Issue by sunjay** [othree/yajs.vim#75]
![screenshot from 2015-10-11 13 41 56](https://cloud.githubusercontent.com/assets/530939/10418038/fc39e6a0-701d-11e5-8ef9-1b4e68b98057.png)

This should be valid syntax and it is being coloured red.

Also this happens when you remove the assignment:
![screenshot from 2015-10-11 13 43 34](https://cloud.githubusercontent.com/assets/530939/10418044/227f032c-701e-11e5-8eae-3e90c2949da7.png)

**Comment by othree** [comment]
The second case is not allow for now.

**Comment by sunjay** [comment]
Thanks

**Comment by shinzui** [comment]
Why is this issue closed? 

![image](https://cloud.githubusercontent.com/assets/519/19024802/2964688c-88c1-11e6-9745-68f2568f6517.png)

`new` should not be highlighted red.

**Comment by sunjay** [comment]
@shinzui your issue is different from (though possibly related to) my issue. That's why this is closed.
