### ISSUE TITLE
Semicolons are red

### ISSUE THREAD

**Issue by sotojuan** [othree/yajs.vim#82]
I am not sure if this is just me and my set up (OS X, macvim, base16-ocean dark scheme), but semicolons are red (same color as `let` or `var`).

IMO semicolons, like variable names, should not have any color.

**Comment by othree** [comment]
Any code sample?

**Comment by sotojuan** [comment]
[Here](http://i.imgur.com/TIs3gA0.jpg) is a screenshot. I have tried other color schemes and in all of them the semicolons have a color that makes them stand out.

**Comment by othree** [comment]
I think current reversion is use `Statement` as highlight group.
Please take a look is there any different.

**Comment by sotojuan** [comment]
I'll take a look later, but all I did to fix my issue was change line 368 of `javascript.vim` to say `Normal` instead of `Exception`. That made the semicolons white, which is what I like.
