### ISSUE TITLE
`else` is not highlighted

### ISSUE THREAD

**Issue by 907th** [othree/yajs.vim#84]
`else` is gray colored. [Screenshot here](http://www.picshare.ru/uploads/151110/ij8oxjmXlG.jpg)

**Comment by othree** [comment]
Hi

Please provide more complete code snippet.
I retype the line but works fine here.

**Comment by 907th** [comment]
Hi! I noticed broken colours with another filetypes today, so it may not to be related to `yajs.vim`. Closing for now. Thank you for your attention!

**Comment by 907th** [comment]
I use NeoVim v0.1.0. Its `:echo version` is `704`.

I'm trying this snippet:
```javascript
let a = 1;
if (a) {
  console.log(a);
} else {
  a = 3;
}
if (!a) a = 4; else a = 6;
```

`if` is highlighted, but `else` is not :(.

If I put cursor to if/else and then try to inspect highlighting group I see `hi<javaScriptConditional> trans<javaScriptConditional> lo<javaScriptConditional>` and `hi<javascriptConditionalElse> trans<javascriptConditionalElse> lo<Conditional>` respectively.

I think `javascriptConditionalElse` is defined by `yajs`, but `javaScriptConditional` defined by standard (Neo)Vim's syntax file for JS.

Any help?

**Comment by 907th** [comment]
Screenshot [here](http://www.picshare.ru/view/6897849/).

**Comment by othree** [comment]
Here I use vim and nvim are all ok on `else`
Do you update to latest reversion?
`javascriptConditionalElse` is defined by yajs but it should link to statement group.
You can try vim-hilinks to get more info

<https://github.com/kergoth/vim-hilinks>

**Comment by 907th** [comment]
@othree I found the reason: my colorscheme (Tomorrow) [has no setting for javascriptConditionalElse](https://github.com/chriskempson/tomorrow-theme/blob/master/vim/colors/Tomorrow-Night-Bright.vim#L347) and falls back [to default Conditional](https://github.com/chriskempson/tomorrow-theme/blob/master/vim/colors/Tomorrow-Night-Bright.vim#L271) which is simply `foreground` colour. (Or something like that, because I don't fully understand how Vim syntax highlighting works). Thank you!
