### ISSUE TITLE
Interferes with omnicompletion

### ISSUE THREAD

**Issue by mhartington** [othree/yajs.vim#85]
So it seems that this will interfere with any other omnicompletion in neovim

Using [Deoplete](https://github.com/Shougo/deoplete.nvim) and [vim-better-javascript-completion](https://github.com/1995eaton/vim-better-javascript-completion) plus this plugin, it seems that vim-better-javascript-completion completion is not able to work.

Using your plugin 

![screen shot 2015-11-12 at 1 24 16 pm](https://cloud.githubusercontent.com/assets/2835826/11127160/caa1e9b2-8940-11e5-9ff8-c15a38fe3fdb.png)

Using `pangloss/vim-javascript`

![screen shot 2015-11-12 at 1 25 46 pm](https://cloud.githubusercontent.com/assets/2835826/11127198/077d66c2-8941-11e5-9739-7ff6bd325310.png)

**Comment by othree** [comment]
That's very strange. Syntax system is complete dependent from omnicomplete complete. The only possible reason is vim-better-javascript-completion use syntax group to tell the complete options.

**Comment by mhartington** [comment]
Yeah not sure what could be causing it. My own viml knowledge is limited, but let me know if you need anymore more info

**Comment by mhartington** [comment]
Found it! Appears that 

autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS

was interfering with the completion plugin. Removing that fixes everything.
