### ISSUE TITLE
Arrow function in object literal value is highlighted red

### ISSUE THREAD

**Issue by sunjay** [othree/yajs.vim#86]
Here's a screenshot
![screenshot from 2015-11-14 12 24 10](https://cloud.githubusercontent.com/assets/530939/11164853/a72c6558-8aca-11e5-8e6f-ceb93065a6ef.png)

**Comment by alnjxn** [comment]
Related but different. Slash in closing tag is highlighted red in JSX files.
<img width="298" alt="screen shot 2015-11-15 at 2 10 02 pm" src="https://cloud.githubusercontent.com/assets/1423708/11170453/bb5480c8-8ba2-11e5-98cb-81f217c1e0a3.png">

**Comment by sunjay** [comment]
Maybe the jsx plugin is conflicting here?

**Comment by alnjxn** [comment]
@sunjay thanks. I don't use the vim-jsx plugin. Just wondering if I should open an issue for this, if others can duplicate or is this the expected behavior.
