### ISSUE TITLE
JSX closing html tag highlighted in red

### ISSUE THREAD

**Issue by alnjxn** [othree/yajs.vim#87]
I brought this up as a comment in #86 but would like to open new issue as it seems unrelated to that issue and its fix. Currently closing tag in JSX is highlighted in red. Here is screenshot and example code. I am *not* using vim-jsx plugin.

![screen shot 2015-11-17 at 2 15 28 pm](https://cloud.githubusercontent.com/assets/1423708/11221925/afb191e0-8d35-11e5-9e23-1e84b14da4fa.png)

```js
var React = require('react');

var Home = React.createClass({

  render: function() {
    return (
      <h2 className='text-center'>
        Search by Github Username Above
      </h2>
    );
  }

});
```

**Comment by othree** [comment]
Hi
yajs don't support JSX.
But it can work with vim-jsx

There are some discussions before <https://github.com/othree/yajs.vim/issues/70>

Is there any reason you don't want to use vim-jsx?

**Comment by alnjxn** [comment]
No reason not to use vim-jsx, just figured one less plugin. Never sure if syntax highlighting plugins are fighting each other in vim. Will have a look through #70 and take a look at vim-jsx. Thank you.

**Comment by othree** [comment]
yajs will only support ES standards(current or future).
There is something called E4X similar to JSX, but already deprecated.
So there is no plan to support this kind of syntax.

Just use vim-jsx if you are writing react and jsx file :smile:
