### ISSUE TITLE
yajs makes Vim slow on comments

### ISSUE THREAD

**Issue by zaferot** [othree/yajs.vim#88]
Hi All. I've just found out that `yajs.vim` makes Vim interface incredibly slow on big comments (e.g. 20 commented lines).

STR:
- Open JavaScript file ~300 loc;
- Comment a block of code ~30 loc;
- Move cursor with `hjkl` withing that area.

You will notice that Vim is slow. Also, if you move away from the commented code (one screen up or down) you see that everything is fine.

P.S. It is not so visible if you disable all plugins except `yajs.vim`.

**Comment by jaapz** [comment]
Is your vim still slow when yajs.vim is disabled? Because I have large comments and I don't have this issue.

**Comment by zaferot** [comment]
Hi @jaapz . Sorry for the delay.
I did some additional testing of this.  If `yajs.vim` is disabled Vim is fine. When only `yajs.vim` is enabled I still experience some lags (not so critical but noticeable).
Also, I noticed that [indentLine](https://github.com/Yggdroot/indentLine) plugin has some influence on the issue. If indentLine is disabled situation on comments is much better. But Vim is still slower than usually.

My `vimrc` is in my profile. This is my Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 30 2015 08:28:28)
Included patches: 1-944
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib

**Comment by FuzzOli87** [comment]
I recently started getting this issue on comments and deep nested object literals as well. I turned off cursorline and it improved significantly.

**Comment by othree** [comment]
I create one test case for this issue <https://github.com/othree/js-syntax-test/blob/master/perf/comment.js>
But not found any difference between comment block and code block.

Indeed yajs.vim have some performance issue.
If it's normal performance issue, please go to #46 .
If you still found heavy lag only in comment block, please let me known.

**Comment by zaferot** [comment]
Hi @othree. Thanks for the response. I don't know what happened, but I don't see the issue right now.
Thank you!

**Comment by XadillaX** [comment]
I have the same issue.

Long comment means a comment maybe spent more then 10 lines? Not Jsdoc comment but to descript something.

**Comment by XadillaX** [comment]
I think `set foldmethod=syntax` + `yajs.vim` makes it slow.
