### ISSUE TITLE
Methods on super are red in certain cases + one other bug

### ISSUE THREAD

**Issue by sunjay** [othree/yajs.vim#89]
Methods called in a subclass on `super` are highlighted red whenever they are called not on their own.
https://babeljs.io/docs/learn-es2015/#classes

See the example below which shows a return statement and no return statement. (This can be anything though, return statements are not the only case.)

Also while preparing this example I found that numbers are not highlighted properly in class names and result in the method name highlighting breaking.

![screenshot from 2015-11-25 16 05 51](https://cloud.githubusercontent.com/assets/530939/11409570/e19b6528-938e-11e5-8363-a321b9de350b.png)

**Comment by othree** [comment]
Do you update to latest reversion?

**Comment by sunjay** [comment]
Even worse in the latest version.
![screenshot from 2015-11-27 16 07 24](https://cloud.githubusercontent.com/assets/530939/11448183/fc2612d8-9520-11e5-95a5-163053a37042.png)

**Comment by othree** [comment]
Can't reproduce.

![2015-12-24 11 38 42](https://cloud.githubusercontent.com/assets/16474/11989122/f2180c84-aa32-11e5-8290-e00a31351e7a.png)

**Comment by sunjay** [comment]
That's strange. How should I go about diagnosing this?

![screenshot from 2015-12-23 21 13 06](https://cloud.githubusercontent.com/assets/530939/11989416/04e960a2-a9ba-11e5-96da-863d2ad4e257.png)

**Comment by sunjay** [comment]
I updated to the latest version before I took that screenshot.

**Comment by sunjay** [comment]
I turned off all my other plugins except othree/yajs and this is still the result:

![screenshot from 2015-12-23 21 16 33](https://cloud.githubusercontent.com/assets/530939/11989442/825b58d8-a9ba-11e5-902b-f3899fb64d31.png)

**Comment by othree** [comment]
If you are willing to help
Could you install vim hilinks[1]?
And see what going on.


[1]:https://github.com/kergoth/vim-hilinks

2015-12-24 12:17 GMT+08:00 Sunjay Varma <notifications@github.com>:

> I turned off all my other plugins except othree/yajs and this is still the
> result:
>
> [image: screenshot from 2015-12-23 21 16 33]
> <https://cloud.githubusercontent.com/assets/530939/11989442/825b58d8-a9ba-11e5-902b-f3899fb64d31.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/89#issuecomment-167039214>.
>



-- 
OOO

**Comment by sunjay** [comment]
I believe I've installed the plugin using `Plugin 'kergoth/vim-hilinks'` but there's no documentation on how to use it. What do you need me to do to be most helpful?

**Comment by othree** [comment]
Doc: https://github.com/kergoth/vim-hilinks/blob/master/doc/hilinks.txt

Basically just execute `:HLT!` and move cursor

2015-12-25 3:58 GMT+08:00 Sunjay Varma <notifications@github.com>:

> I believe I've installed the plugin using Plugin 'kergoth/vim-hilinks'
> but there's no documentation on how to use it. What do you need me to do to
> be most helpful?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/othree/yajs.vim/issues/89#issuecomment-167154684>.
>



-- 
OOO

**Comment by sunjay** [comment]
Hi @othree,
Sorry this took so long.

![screenshot from 2016-02-11 22 15 18](https://cloud.githubusercontent.com/assets/530939/12998041/0a734ad6-d10d-11e5-800e-fb65018438b7.png)
![screenshot from 2016-02-11 22 15 23](https://cloud.githubusercontent.com/assets/530939/12998040/0a729eba-d10d-11e5-913e-a1d9bf720e7e.png)

**Comment by othree** [comment]
Sorry I didn't notice you have reply this issue.

I can't reproduce.
`return` should be highlight.
`super` is in <https://github.com/othree/es.next.syntax.vim>

I think there are two possible cause reason:

1. Your filetype is incorrect, should be `javascript`
2. There are other plugin interrupt this

So maybe you can try disable all other plugins and try again.

**Comment by sunjay** [comment]
I'll close this for now since I don't have time to investigate. I'll open again if it becomes a problem.
