### ISSUE TITLE
Add support for default values for function arguments

### ISSUE THREAD

**Issue by jaapz** [othree/yajs.vim#94]
This is valid es6:

```javascript
    let myFunctionWithDefaults = function(someNormalArgument, 
                                          argumentWithDefaultValue='default') {
         ... function body ...
    }
```

But the argument with default value is not highlighted for me.
Could you add support for this syntax?

**Comment by othree** [comment]
I think this is already in.

**Comment by jaapz** [comment]
@othree Well it does not work for me, does it work for you? I have yajs.vim installed through vundle.

**Comment by othree** [comment]
Maybe conflict with other stuff, or you are not on latest reversion?

**Comment by jaapz** [comment]
I just checked, and I am on a the latest commit in the master branch. Is there any way I can make sure the yajs.vim syntax file is actually used? Although I'm pretty sure it is.

**Comment by jaapz** [comment]
I'm sorry, turns out I did have an extra javascript syntax file that was being used instead of yajs...
