### ISSUE TITLE
ES2015 template string with path

### ISSUE THREAD

**Issue by davidosomething** [othree/yajs.vim#98]
```
var path = `${dirs.css.dist}/**/*`;
console.log();
```

Because there is a glob path there containing a `/**/*`, looks like a comment the end backtick does not match and rest of file is interpreted as a comment

![00000066](https://cloud.githubusercontent.com/assets/609213/11879170/c1eedc10-a4c7-11e5-8a88-add4fce042c5.png)

**Comment by othree** [comment]
Can't reproduce.

![2015-12-24 11 30 31](https://cloud.githubusercontent.com/assets/16474/11989019/cdc56e18-aa31-11e5-9f08-4896285d67a3.png)

**Comment by davidosomething** [comment]
whoops, determined that this is caused by https://github.com/othree/jsdoc-syntax.vim

**Comment by othree** [comment]
I am using jsdoc-syntax too.
Make sure you use latest jsdoc-syntax and see is any difference.
